prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  

template sh:and (?shape, ?sh, ?and, ?vis, ?ls) {
  sh:safe(?shape, ?sh, ?suc)
}
where {
    values ?s { unnest(?ls) }
 
    bind (java:and(?and, ?s, ?shape) as ?count)  
	bind (! bound(?count) AS ?failure) .
	bind (IF (?failure, false, ?count)  as ?suc)
	
    bind (java:report(sh:and, ?sh, ?shape, ?s, st:null, ?s, ?suc, ?vis) as ?b)
  
}


