#
#  ?ls is the list of target nodes of shape ?sh
#  evaluate  sh:and sh:or sh:not
#
prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  

template  (?shape, ?sh, ?vis, ?ls) {
   st:call-template(?bool, ?shape, ?sh, ?cst, ?vis, ?ls)
}
where {
    graph ?shape {  
        values ?bool { sh:and sh:or sh:xone sh:not } 
        ?sh ?bool ?cst
    }
}

