#
#  ?ls is the list of target nodes of shape ?sh
#  evaluate sh:constraint
#
prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?ls) {
  sh:safe(?shape, ?sh, ?suc)
}
where {
    graph ?shape { filter not exists { ?sh sh:path ?ppp } }
    
    bind (sh:hasConstraint(?shape, ?sh, ?vis, ?ls) as ?suc)
  
}


