#
# create a table for qualifiedValueShapesDisjoint
# table is used by path/qualified
# it records the list of list of values for each subject
# table is used by core/disjoint2
#
prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?list) {
    true
}
where {
    graph ?shape {  
        ?sh sh:qualifiedValueShapesDisjoint true  
        filter not exists { ?sh sh:deactivated true}
    }
    
    bind (st:cset(?sh, ?sh, xt:list()) as ?init)
    
}
pragma { st:template st:priority 1 } 



