prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  

template sh:not (?shape, ?sh, ?cst, ?vis, ?ls) {
  sh:safe(?shape, ?sh, ?suc)
}
where {

    values ?s { unnest(?ls) }
    bind (! java:testShapeCore(?shape, ?cst, ?s) as ?suc)
    
    bind (java:report(sh:not, ?sh, ?shape, ?s, st:null, ?s,  ?suc, ?vis) as ?b)
  
}
