prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:not (?shape, ?sh, ?cst, ?vis, ?ls) {
  sh:safe(?shape, ?sh, ?suc)
}
where {

    values ?s { unnest(?ls) }
    bind (! sh:testShapeCore(?shape, ?cst, ?s) as ?suc)
    
    bind (st:report(sh:not, ?sh, ?shape, ?s,  ?suc, ?vis) as ?b)
  
}
