prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s) {
  sh:safe(?shape, ?sh, ?suc)
}
where {
    graph ?shape { 
        ?sh sh:property ?cst  
        optional { ?cst sh:filterShape ?fs } 
        filter (! bound(?fs) || st:testShape(?shape, ?fs, ?s)) 
        ?cst sh:path ?p
    }
  
    bind (sh:hasPath(?shape, ?cst, ?vis, ?s, ?p) as ?suc)
  
}
