#
# evaluate sh:qualifiedValueShape sh:path of shape ?prop
# ?list is the list of target nodes of shape ?sh
#
prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?list) {
   sh:safe(?shape, ?sh, ?suc)
}
where {
    graph ?shape {  
        ?prop sh:qualifiedValueShape ?sh  
        ?sh sh:path ?p 
        ?gsh sh:property ?prop
        filter not exists { ?sh sh:deactivated true}
    }
        
    bind (sh:path(?shape, ?sh, ?vis, ?list, ?p) as ?suc)
}


