template {
	?suc
}
where {
	?in rdfs:subClassOf ?y
	
	filter (
		isURI(?in) ||
		not exists { ?x ?p ?in }
	)
	
	bind (
		st:call-template-with(st:subexpowlqltc, st:subClassExpression, ?in) &&
		st:call-template-with(st:superexpowlqltc, st:superClassExpression, ?y)
	as ?suc)
	
	filter(st:alreadyVisited(?in, "subClass", ?suc))
}