template st:subClassExpression(?x) {
  ?suc
}
where {
    bind (
      if (isURI(?x), ?x != owl:Thing, 
         st:apply-templates-all(?x))
    as ?suc)
    
#  filter(st:visit(st:sub, ?x, ?suc))
	filter(st:alreadyVisited(?x, "sub", ?suc))
}
