#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  st:kw( "graph") " " ?g " {" 
  box {
    if (?b = rdf:nil, "", 
      st:call-template(sp:listnl, ?b))
  }
  "}"
}
where {
  ?in a sp:NamedGraph ;
    sp:graphNameNode ?g ;
    sp:elements  ?b
}



