#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template sp:list {
  if (?b, "\n  ", "")
  ?exp  ; separator = " "
}
where {
  ?in rdf:rest*/rdf:first ?exp
  bind ( exists { ?exp sp:expression ?e } as ?b )
}




