#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:<http://spinrdf.org/sp#> .

template  {
  "(" st:call-template(sp:list, ?val)    ")"
}
where {
  ?x sp:values ?in
  ?in rdf:rest*/rdf:first ?val
}



