#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template{
  "?" xsd:string(?var)
}
where {
  ?in sp:varName ?var 
  filter not exists { ?in sp:expression ?e }
}



