#
# Turtle Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
template {

  if (us:myerror(?in), "<span class='fail'>", "")
  ?in 
  if (us:myerror(?in), "</span>", "")      
     
ibox { 
	st:nl()
	st:call-template(st:value, ?in)
} 
            
" ."      
}
where {
  ?in ?p ?y   
  filter isUri(?in)
}
limit 1
