#
# Turtle Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
template st:value {

format {
    if (?p = rdf:type, "<span class='type'>a %2$s</span>", "%s %s")
    
	st:process(?p)  	       
	if (?refer, st:turtle(?y), 
        if (isURI(?y) && ?y = rdf:nil, "()", st:process(?y)))
}
             
   ; separator = concat(" ;", st:nl()) 
}
where {
  ?in ?p ?y 
    
  bind (
    isBlank(?y) 
    && ( (st:isStart() && exists { ?x ?q ?y . filter(?in != ?x) })
         || exists { ?y ?q ?y } 
         || ?in = ?y
       )
  as ?refer)
    
}
order by if (?p = rdf:type, 0, 1) ?p ?y
