#
# URI <http://ns.inria.fr/sparql-template/date/10/2015>
# translated as "10/2015"^^xsd:gYearMonth
#
template st:month {

  st:call-template(st:title, ?date)

  format {

    """
    <p>
    <table class='table'>
      <tr style='vertical-align: bottom'>
      %s
      </tr>
    </table>
    </p>
    """
    
    st:call-template(st:dbpediafor, ?date)
    
  }
  
  st:call-template(st:title, ?date)
  
  st:call-template(st:tail)
 
}
where {

#   bind (st:set(st:uri, <http://ns.inria.fr/sparql-template/date/09/2015>) as ?dd)
#   bind (st:set(st:profile, st:dbedit) as ?tt)
#   bind (st:set(st:service, "template") as ?ss)

   bind (st:get(st:uri) as ?uri)
   bind (strafter(?uri, us:root()) as ?str)
   bind (strdt(?str, xsd:gYearMonth) as ?date)
   bind (st:set(st:date, ?date) as ?tmp)
   
#   filter kg:display(?date)
}