template st:title(?date) {

  format {
  """
  <h2 class='center'> %s &lt;&lt; %s &lt; Edition DBpedia %s > %s >> %s </h2>
  """
  
   st:call-template(st:link, us:year(?date, -1))
   st:call-template(st:link, us:before(?date))
   ?date
   st:call-template(st:link, us:after(?date))
   st:call-template(st:link, us:year(?date, 1))
  }
  
}
where {
    
}