prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  
template {
    "(" group { ?path ; separator = " | " } ")"
}
where {
    ?in sh:alternativePath/rdf:rest*/rdf:first ?path
}

