prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  
template {
    "(" ?path ") +"
}
where {
    ?in sh:oneOrMorePath ?path
}

