//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 10:15:40 AM CEST 
//


package fr.inria.edelweiss.rif.xml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.inria.edelweiss.rif.xml.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("http://www.w3.org/2007/rif#", "Name");
    private final static QName _SlotFrameTypeExternal_QNAME = new QName("http://www.w3.org/2007/rif#", "External");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.inria.edelweiss.rif.xml.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link And }
     * 
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link Directive }
     * 
     */
    public Directive createDirective() {
        return new Directive();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link IRICONSTType }
     * 
     */
    public IRICONSTType createIRICONSTType() {
        return new IRICONSTType();
    }

    /**
     * Create an instance of {@link ContentFORMULAType }
     * 
     */
    public ContentFORMULAType createContentFORMULAType() {
        return new ContentFORMULAType();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Equal }
     * 
     */
    public Equal createEqual() {
        return new Equal();
    }

    /**
     * Create an instance of {@link AndThenType }
     * 
     */
    public AndThenType createAndThenType() {
        return new AndThenType();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link Args }
     * 
     */
    public Args createArgs() {
        return new Args();
    }

    /**
     * Create an instance of {@link fr.inria.edelweiss.rif.xml.schema.Formula }
     * 
     */
    public fr.inria.edelweiss.rif.xml.schema.Formula createFormula() {
        return new fr.inria.edelweiss.rif.xml.schema.Formula();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link ExternalTERMType }
     * 
     */
    public ExternalTERMType createExternalTERMType() {
        return new ExternalTERMType();
    }

    /**
     * Create an instance of {@link Payload }
     * 
     */
    public Payload createPayload() {
        return new Payload();
    }

    /**
     * Create an instance of {@link ANYURICONSTType }
     * 
     */
    public ANYURICONSTType createANYURICONSTType() {
        return new ANYURICONSTType();
    }

    /**
     * Create an instance of {@link Expr }
     * 
     */
    public Expr createExpr() {
        return new Expr();
    }

    /**
     * Create an instance of {@link Forall.Formula }
     * 
     */
    public Forall.Formula createForallFormula() {
        return new Forall.Formula();
    }

    /**
     * Create an instance of {@link SlotUNITERMType }
     * 
     */
    public SlotUNITERMType createSlotUNITERMType() {
        return new SlotUNITERMType();
    }

    /**
     * Create an instance of {@link Right }
     * 
     */
    public Right createRight() {
        return new Right();
    }

    /**
     * Create an instance of {@link Op }
     * 
     */
    public Op createOp() {
        return new Op();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Subclass }
     * 
     */
    public Subclass createSubclass() {
        return new Subclass();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Forall }
     * 
     */
    public Forall createForall() {
        return new Forall();
    }

    /**
     * Create an instance of {@link Or }
     * 
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Super }
     * 
     */
    public Super createSuper() {
        return new Super();
    }

    /**
     * Create an instance of {@link FormulaThenType }
     * 
     */
    public FormulaThenType createFormulaThenType() {
        return new FormulaThenType();
    }

    /**
     * Create an instance of {@link Left }
     * 
     */
    public Left createLeft() {
        return new Left();
    }

    /**
     * Create an instance of {@link Then }
     * 
     */
    public Then createThen() {
        return new Then();
    }

    /**
     * Create an instance of {@link Const }
     * 
     */
    public Const createConst() {
        return new Const();
    }

    /**
     * Create an instance of {@link Rest }
     * 
     */
    public Rest createRest() {
        return new Rest();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentence() {
        return new Sentence();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link Atom }
     * 
     */
    public Atom createAtom() {
        return new Atom();
    }

    /**
     * Create an instance of {@link Frame }
     * 
     */
    public Frame createFrame() {
        return new Frame();
    }

    /**
     * Create an instance of {@link SlotFrameType }
     * 
     */
    public SlotFrameType createSlotFrameType() {
        return new SlotFrameType();
    }

    /**
     * Create an instance of {@link Implies }
     * 
     */
    public Implies createImplies() {
        return new Implies();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link FormulaMetaType }
     * 
     */
    public FormulaMetaType createFormulaMetaType() {
        return new FormulaMetaType();
    }

    /**
     * Create an instance of {@link Declare }
     * 
     */
    public Declare createDeclare() {
        return new Declare();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link AndMetaType }
     * 
     */
    public AndMetaType createAndMetaType() {
        return new AndMetaType();
    }

    /**
     * Create an instance of {@link ContentTERMType }
     * 
     */
    public ContentTERMType createContentTERMType() {
        return new ContentTERMType();
    }

    /**
     * Create an instance of {@link ExternalFORMULAType }
     * 
     */
    public ExternalFORMULAType createExternalFORMULAType() {
        return new ExternalFORMULAType();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Exists }
     * 
     */
    public Exists createExists() {
        return new Exists();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2007/rif#", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalTERMType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2007/rif#", name = "External", scope = SlotFrameType.class)
    public JAXBElement<ExternalTERMType> createSlotFrameTypeExternal(ExternalTERMType value) {
        return new JAXBElement<ExternalTERMType>(_SlotFrameTypeExternal_QNAME, ExternalTERMType.class, SlotFrameType.class, value);
    }

}
