#
# Turtle Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
template st:main { 
    st:apply-templates(?x)  " ."
    ; separator = "\n\n"
}
where {
  select distinct ?x where { 
    bind (st:focus() as ?x)
    
    ?x ?p ?y  
    
    filter ( 
      isURI(?x) 
      || not exists { ?z ?q ?x }
      || (isBlank(?x) 
        && not exists { ?x rdf:first ?e }
        && ( if (exists { ?a ?q ?x . ?b ?r ?x . filter(?a != ?b) }, st:cset(st:refer, ?x, true), false)
              || exists { ?x ?q ?x } )
	     )
    )
  } order by ?x
}

