#
# Geolocate  resources on a map 
# ?list = list(list(uri, lat, lon, val))
#
prefix ft:   <http://ns.inria.fr/sparql-template/format/sensor/>
prefix ex: <http://example.org/> .

template st:gmap2(?list) {
  format {
    <ft:map2.html>
    
    st:number()
    str(?lat)
    str(?lon)
    coalesce(us:icon(us:num(?val)), "/img/greenmarker.png")
    st:plink(?r)
  }
}
where {

  values (?r ?lat ?lon ?val) { unnest(?list) }
  
}


function us:num(?val) {
    us:absolute(?val)
}


function us:absolute(?val) {
    if (isNumeric(?val),
        if (?val >= 60, 4, 
        if (?val >= 30, 3, 
        if (?val >= 15, 2, 1))),
    0)
}



# 0 is good, greater is worse
function us:icon(?n) {
    let (?list = @(
    "/img/bluemarker.png" "/img/bluemarker.png"  "/img/greenmarker.png" 
    "/img/pinkmarker.png" "/img/blackmarker.png"
    "https://cdn4.iconfinder.com/data/icons/48x48-free-object-icons/48/Red_pin.png" 
    )) {
        if (?n >= xt:size(?list),  us:icon(0), xt:get(?list, ?n))
    }
}



# 0 <= val <= 100
# 0 is good, 100 is bad

function us:relative(?val) {
    if (isNumeric(?val),
        if (?val >= st:cget(st:quart3, ex:AirQualityIndex), 4, 
        if (?val >= st:cget(st:median, ex:AirQualityIndex), 3, 
        if (?val >= st:cget(st:quart1, ex:AirQualityIndex), 2, 1))),
    0)
}

