prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {
    ?sh sh:classIn ?lc                     
  }
  
  bind (
    exists { graph ?shape { ?lc rdf:rest*/rdf:first ?c } 
        ?s rdf:type/rdfs:subClassOf* ?c }    
  as ?suc)
  
  bind (st:report(sh:classIn, ?sh, ?shape, ?s, ?s, rdf:type, "in", ?suc, ?vis) as ?b)
}
