prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:class (?shape, ?sh, ?vis, ?s, ?c){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  bind (exists { ?s rdf:type/rdfs:subClassOf* ?c } as ?suc)
  bind (st:report(sh:class, ?sh, ?shape,  ?s, rdf:type, ?s, ?suc, ?vis) as ?b)
}

