prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:datatype (?shape, ?sh, ?vis, ?s, ?d){
  sh:safe(?shape, ?sh, ?suc)
}
where {
  
  bind (sh:datatype(?s, ?d)  as ?suc)
  
  bind (st:report(sh:datatype, ?sh, ?shape, ?s, st:null, ?s, ?suc, ?vis) as ?b)
}
