prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:equals (?shape, ?sh, ?vis, ?s, ?p){
     st:call-template(?oper, ?shape, ?sh, ?vis, ?s, ?p)
}
where {

  values ?oper {sh:equals1 sh:equals2}

}
