prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  

template sh:equals (?shape, ?sh, ?vis, ?s, ?p){
     st:call-template(?oper, ?shape, ?sh, ?vis, ?s, ?p)
}
where {

  values ?oper {sh:equals1 sh:equals2}

}
