prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?ls) {
    st:call-template(?q, ?shape, ?sh, ?vis, ?s, ?m)
}
where {
  graph ?shape {  
    values ?q { sh:class  sh:pattern sh:sparql }
    ?sh ?q ?m            
    #filter not exists { ?sh sh:path ?p }

  }
  
  values ?s { unnest(?ls) }
}


