prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s) {
  sh:safe(?shape, ?sh, ?suc)
}
where {
  graph ?shape {  
    ?sh sh:minInclusive|sh:minExclusive|sh:maxInclusive|sh:maxExclusive ?m ; ?q ?m                       
  }
  bind ( 
    coalesce(
        if (?q = sh:minInclusive, ?s >= ?m,
        if (?q = sh:minExclusive, ?s > ?m,
        if (?q = sh:maxInclusive, ?s <= ?m, 
            ?s < ?m))), 
    false) 
  as ?suc )
  
  bind (st:report(?q, ?sh, ?shape, ?s, ?suc, ?vis) as ?b)
}

