prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s) {
  sh:safe(?shape, ?sh, ?suc)
}
where {
  graph ?shape {  
    ?sh sh:stem ?exp   
  }
  bind (isURI(?s) && strstarts(?s, ?exp)
  as ?suc )

  bind (st:report(sh:stem, ?sh, ?shape, ?s, ?suc, ?vis) as ?b)
}

