prefix msh: <http://ns.inria.fr/shacl/>

@import <function/datashape/main.rq> <function/datashape/ppath.rq> <function/datashape/operator.rq> <function/datashape/core.rq> 

template st:profile {}
where {}

function st:aggregate(out) {
  st:agg_and(out)
  #aggregate(out, us:merge)
}

function us:merge(list) {
    reduce(rq:and, list)
}

function st:default(term){
    true
}

function st:defaultNamed(term){
    true
}

function st:optimize(shape, sh){
    true
}


