BASE <http://www.southgreen.fr/agrold/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo:<http://purl.obolibrary.org/obo/>
PREFIX taxon:<http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX uniprot:<http://purl.uniprot.org/uniprot/>
PREFIX vocab:<vocabulary/>
PREFIX graph:<protein.annotations>

@trace
@federation <http://fed.corese.inria.fr/d2kab/sparql>
#@include <http://agrold.southgreen.fr/sparql> 

SELECT distinct ?protein ?name ?evidence ?evidence_label ?evidence_code
WHERE {
 GRAPH graph: {
    {
     ?protein vocab:taxon taxon:4565.
     ?protein rdfs:label ?name.
      {     
       ?protein ?p obo:GO_0048364.
       ?protein vocab:has_annotation ?bp.
       ?bp rdf:subject ?protein.
       ?bp rdf:object obo:GO_0048364.
       ?bp vocab:evidence_code ?evidence_code.
       ?bp vocab:evidence ?evidence.       
      } UNION {
       ?protein ?p obo:GO_2000280.
       ?bp rdf:subject ?protein.
       ?protein vocab:has_annotation ?bp. 
       ?bp rdf:object obo:GO_2000280.
       ?bp vocab:evidence_code ?evidence_code.
       ?bp vocab:evidence ?evidence.
      }
    } UNION {
     ?protein vocab:taxon taxon:4572.
     ?protein rdfs:label ?name.
      {     
       ?protein ?p obo:GO_0048364.
       ?protein vocab:has_annotation ?bp.
       ?bp rdf:subject ?protein.
       ?bp rdf:object obo:GO_0048364.
       ?bp vocab:evidence_code ?evidence_code.
       ?bp vocab:evidence ?evidence.       
      } UNION {
       ?protein ?p obo:GO_2000280.
       ?protein vocab:has_annotation ?bp. 
       ?bp rdf:subject ?protein.
       ?bp rdf:object obo:GO_2000280.
       ?bp vocab:evidence_code ?evidence_code.
       ?bp vocab:evidence ?evidence.               
      }    
    }
 }
 
GRAPH ?g {
    ?evidence rdfs:label ?evidence_label.
}
} 
limit 10


