#
# Generate link for URI
#
template st:display(?x) {

  if (! bound(?profile)){ 
    st:call-template(st:esc, ?x) 
  }
  else if (?profile = st:std){ 
    st:call-template(st:linkesc, ?x) 
  }
  else if (st:lod(?x)){
    st:call-template(st:linkesc, ?x)
  }
  else { 
    st:call-template(st:linkprofile, ?x) 
  }
          
}
where {
      bind (st:get(st:profile) as ?profile)
}
