template st:esc(?x) {

  str(?tt)
    
}
where {

   bind(st:turtle(?x) as ?t)
   
   bind (
    let (?t = st:turtle(?x)) { replace(?t, "<", "&lt;") } 
   as ?tt)
   
#   bind(if (isURI(?x) && strstarts(?t, "<"), str(?x), ?t) as ?d) 
    
}
