prefix rs: <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>
template st:open {

  """
  <h3>Result</h3>
  <table>
  """
  
 "<tr class='s1'><td/>"
 
  st:call-template(st:th)
  
 "</tr>\n"
}
where {
}
