prefix rs: <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>
template st:open {

format {

  """
  <table class='table'>    
  <tr><td/>%s</tr>\n
  """
 
 st:call-template(st:th)
 }
}
where {
}
