template st:profile {
  
}
where {}
  
  # LOD URI hypertext link generated as is (see display.rq)
  # set by profile.ttl : st:param [ st:lod (URI) ]
  function st:lod(?x){
     coalesce(mapany(rq:strstarts, ?x, st:get(st:lod)), false)
  }

