#
#  Get an optional icon from the dataset and display it
#
template st:show(?x) {
    format { "<img width='35' src='%s' />"  str(?l) }
}
where {
  bind (st:get(st:dataset) as ?g)
  graph ?g { 
    { ?x st:icon ?l }  
    union { ?x a ?t . ?t st:icon ?l }  
  }
}
limit 1