template st:tablecons {

 "<tr class='s" 
   if (kg:even(st:number()), 1, 0)
 "'>"
 "<th>"      st:number()
 "</th><td>" st:call-template(st:show,    ?x) 
 "</td><td>" st:display(?x) 
 "</td><td>" st:display(?p) 
 "</td><td>" st:display(?y) 
 "</th><td>" st:call-template(st:show,    ?y) 
 "</td>"
 "</tr>"
 
}
where {
  ?x ?p ?y
  bind (st:get(st:uri) as ?uri)
  filter (if (bound(?uri), ?uri in (?x, ?p, ?y), true))
}
order by ?x ?p ?y


