template st:tablecons3(?x) {
"<table>"
group  {
 "<tr>"
 "<td>" st:display(?p) 
 "</td><td>" st:display(?y) 
 "</th><td>" st:call-template(st:show,    ?y) 
 "</td>"
 "</tr>"
 }
 "</table>"
 
}
where {
  ?x ?p ?y
  bind (st:get(st:uri) as ?uri)
  filter (if (bound(?uri), ?uri in (?x, ?p, ?y), true))
}
order by ?x ?p ?y