prefix h: <http://www.inria.fr/2015/humans#>

@federate <http://corese.inria.fr/sparql> <http://fr.dbpedia.org/sparql>
@trace 
select * where {
    ?s h:name ?n .
    ?s h:hasFriend ?f ;
    h:hasChild ?c  .
}
