PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

@federation @index
@include <http://dbpedia.org/sparql>
          <http://data.semanticweb.org/sparql>
@trace
SELECT ?President ?Party WHERE {
?President rdf:type dbpedia-owl:President 
?President dbpedia-owl:party ?Party . 
}
