#
# skip undefined exists
#
prefix fcu: <http://ontology.inrae.fr/frenchcropusage/>

@trace 
@federation <http://fed.corese.inria.fr/d2kab/sparql>
@federateUndefined true
SELECT * 
WHERE {    
    ?dummy skos:prefLabel "arboriculture"@fr .
    filter not exists {?s fcu:undefined ?o}
   
} 

