#
#
# Olivier Corby - Wimmics - INRIA I3S UNS CNRS - 2015
#
prefix tc: </user/corby/home/AData/template/spintc/>

template st:start {
  us:boolean(st:apply-templates-with-all(st:spintcbody))
}
where {
}


function us:boolean(?x) {
    return (! contains(?x, "false"))
}
