template st:listrec(?y) {
format {
"<rdf:Description>%s</rdf:Description>" 
   
   box {
    
   st:call-template(st:triple, ?y, rdf:first, ?f)
   st:nl()
   
   if (?r = rdf:nil, 
      st:apply-templates(?y, rdf:rest, ?r),
      st:call-template(st:listrecrest, ?r))   
   }
}
}
where {
  ?y rdf:first ?f ;
     rdf:rest  ?r
}
