template (?x, ?p, ?y) {
format {
   "<%s xml:lang='%s'>%s</%s>"
   
   st:turtle(?p, true)
   lang(?y)
   st:literal(str(?y))
   st:turtle(?p, true)
}   
}
where {
   ?x ?p ?y
   filter (isLiteral(?y) && datatype(?y) = rdf:langString)
}
