template (?x, ?p, ?y) {
format {
   "<%s rdf:datatype='%s'>%s</%s>"
   
   st:turtle(?p, true)
   if (strstarts(datatype(?y), xsd:), replace(datatype(?y), xsd:, "&xsd;"), datatype(?y)) 
   st:literal(str(?y)) 
   st:turtle(?p, true)
}
}
where {
   ?x ?p ?y
   filter (isLiteral(?y) 
   && datatype(?y) != rdf:langString
   && datatype(?y) != xsd:string)
}
