#
# select top level terms ?in
# URI
# Top level bnodes (not object of a property)
#
template st:main {
   st:call-template(st:resource, ?in)
   ; separator = "\n\n"
}
where {
   select distinct ?in where {
     ?in ?p ?y
     
     filter (isURI(?in) || ! exists { ?x ?q ?in } )
     
   }
   order by ?in
}
