template st:profile {}
where {}

function st:literal(?x){
    if (st:get(st:html, true), 
        ?x, 
        #st:format("<span class='literal'>%s</span>", ?x), 
        ?x)
}

function us:clean(?x) {
    replace(replace(?x, "&", "&amp;"), "<", "&lt;")
}
