template st:resourceref(?in) {
format {
  "<rdf:Description %s='%s' />" 
  
  st:turtle(?att)
  str(?name)
}
}
where {
   bind ( if (isBlank(?in), rdf:nodeID, rdf:about) as ?att)
   bind ( if (isBlank(?in), ?in, ?in) as ?name)
}

