template st:resource(?in, ?t) {
format {
    "<%s %s='%s'>%s</%s>"
    
    st:turtle(?tag, true)
    st:turtle(?att) 
    str(?name)
    box { 
        if (bound(?t), 
            st:call-template(st:property, ?in, ?t),
            st:call-template(st:property, ?in))
    }
    st:turtle(?tag)
}
}
where {
   bind (if (isBlank(?in), rdf:nodeID, rdf:about) as ?att)
   bind (if (isBlank(?in), ?in, ?in) as ?name)
   bind (if (bound(?t), ?t, rdf:Description) as ?tag)
}

