#
# RDF/XML Transformation
#
# Olivier Corby - Wimmics INRIA I3S - 2015
#

template st:start(?in) {

  st:call-template(st:head)
  
  str(?body)
  
  st:call-template(st:tail)
}
where {
   bind(
    if (bound(?in), st:call-template(st:main, ?in), st:call-template(st:main)) 
   as ?body )
}
