#
# Trig Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2014
#
template st:graph {
  format {
  """graph %s {%s}"""
  
  st:turtle(?g)
  box {
       st:apply-templates-with-graph(<http://ns.inria.fr/sparql-template/turtle#main>, ?g) 
    }
  }
  ; separator = "\n\n"
}
where {
  select ?g where {
    graph ?g {
      filter exists { ?x ?p ?y }
    }
  }
}
order by ?g 
