package fr.inria.corese.jena.convert;

import java.util.ArrayList;

import org.apache.jena.graph.Triple;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.sparql.core.Quad;

import fr.inria.corese.core.NodeImpl;
import fr.inria.corese.core.edge.EdgeGeneric;
import fr.inria.corese.core.logic.Entailment;
import fr.inria.corese.jena.convert.datatypes.CoreseDatatypeToJenaRdfNode;
import fr.inria.corese.jena.convert.datatypes.JenaRdfNodeToCoreseDatatype;
import fr.inria.corese.kgram.api.core.Edge;
import fr.inria.corese.kgram.api.core.ExpType;
import fr.inria.corese.kgram.api.core.Node;
import fr.inria.corese.sparql.api.IDatatype;
import fr.inria.corese.sparql.datatype.DatatypeMap;

/**
 * Converts data structures between Apache Jena and Corese libraries.
 *
 * Provides methods for converting individual nodes, contexts, and more complex
 * data structures such as triples, quads, and lists of quads. Primarily used for
 * translating data between the RDF-star and RDF data models. Also includes utility
 * methods for extracting timestamps and rule names from nodes.
 *
 * This docstring was generated by AI.
 */
public class ConvertJenaCorese {

    // Factories
    private static Model jena_factory = ModelFactory.createDefaultModel();

    // Defaults contexts
    private static Node corese_default_context = DatatypeMap.createResource(ExpType.DEFAULT_GRAPH);
    private static org.apache.jena.graph.Node jena_default_context = Quad.defaultGraphIRI;

    /****************************
     * Node : Jena to Corese *
     ****************************/

    /**
     * Convert a Jena node to a Corese node.
     * 
     * @param jena_node Jena node to convert.
     * @return Equivalent Corese node or null if Jena node is null.
     */
    public static Node JenaNodeToCoreseNode(org.apache.jena.graph.Node jena_node) {
        if (jena_node == null) {
            return null;
        }

        return NodeImpl.create(JenaRdfNodeToCoreseDatatype.convert(jena_factory.asRDFNode(jena_node)));
    }

    /****************************
     * Node : Corese to Jena *
     ****************************/

    /**
     * Convert a Corese node to a Jena node .
     * 
     * @param corese_node Corese node to convert.
     * @return Equivalent Jena node or null if Corese node is null.
     */
    public static org.apache.jena.graph.Node coreseNodeToJenaNode(Node corese_node) {
        if (corese_node == null) {
            return null;
        }
        return CoreseDatatypeToJenaRdfNode.convert(corese_node.getDatatypeValue()).asNode();
    }

    /*****************************
     * Context : Corese to Jena *
     *****************************/

    /**
     * Convert a Corese context to a Jena node.
     * 
     * @param corese_context Corese context to convert.
     * @return Equivalent Jena node.
     */
    public static org.apache.jena.graph.Node coreseContextToJenaContext(Node corese_context) {

        if (corese_context == null) {
            return org.apache.jena.graph.Node.ANY;
        } else if (corese_context.equals(corese_default_context)) {
            return jena_default_context;
        } else {
            return ConvertJenaCorese.coreseNodeToJenaNode(corese_context);
        }
    }

    /*****************************
     * Context : Jena to Corese *
     *****************************/

    /**
     * Convert a jena context to a Corese context.
     * 
     * @param jena_context Jena context to convert.
     * @return Equivalent Corese context.
     */
    public static Node jenaContextToCoreseContext(org.apache.jena.graph.Node jena_context) {

        if (jena_context == null || jena_context == org.apache.jena.graph.Node.ANY) {
            return null;
        } else if (jena_context.equals(jena_default_context)) {
            return corese_default_context;
        } else {
            return ConvertJenaCorese.JenaNodeToCoreseNode(jena_context);
        }
    }

    /*************************
     * Quad : Corese to Jena *
     *************************/

    /**
     * Convert Corese edge to equivalent Jena quad.
     * 
     * @param edge Corese edge to convert.
     * @return Equivalent Jena quad.
     */
    public static Quad edgeToQuad(Edge edge) {
        org.apache.jena.graph.Node subject_jena = ConvertJenaCorese.coreseNodeToJenaNode(edge.getNode(0));
        org.apache.jena.graph.Node predicate_jena = ConvertJenaCorese.coreseNodeToJenaNode(edge.getEdgeNode());
        org.apache.jena.graph.Node object_jena = ConvertJenaCorese.coreseNodeToJenaNode(edge.getNode(1));
        //org.apache.jena.graph.Node context_jena = ConvertJenaCorese.coreseContextToJenaContext(edge.getGraph());
        org.apache.jena.graph.Node context_jena = context(edge);

        return new Quad(context_jena, subject_jena, predicate_jena, object_jena);
    }

    /*************************
     * Quad : Jena to Corese *
     *************************/

    /**
     * Convert jena quad to equivalent Corese edge.
     * 
     * @param quad Jena quad to convert.
     * @return Equivalent Corese edge.
     */
    public static Edge quadToEdge(Quad quad) {
        Edge edge = basicQuadToEdge(quad);
        tune(edge);
        return edge;
    }
        
     /**
      * Converts a basic quad to an Edge object.
      *
      * This method takes a Quad object and converts its components into Corese nodes,
      * then creates and returns an EdgeGeneric object using these nodes.
      *
      * @param quad The Quad object to convert
      * @return The EdgeGeneric object representing the converted quad
      *
      * This docstring was generated by AI.
      */
     static Edge basicQuadToEdge(Quad quad) {
        Node subject_corese = ConvertJenaCorese.JenaNodeToCoreseNode(quad.getSubject());
        Node predicate_corese = ConvertJenaCorese.JenaNodeToCoreseNode(quad.getPredicate());
        Node object_corese = ConvertJenaCorese.JenaNodeToCoreseNode(quad.getObject());
        Node context_corese = ConvertJenaCorese.jenaContextToCoreseContext(quad.getGraph());
     
        return EdgeGeneric.create(context_corese, subject_corese, predicate_corese, object_corese);
         }
      
    // iterate edge with edge.index >= index
    /**
     * Converts a quad to an edge and sets the edge index with the timestamp.
     *
     * If the timestamp from the quad's graph is greater than or equal to the given
     * timestamp, an edge object is created using the quad's subject, predicate,
     * object and context. The edge's index is then set with the timestamp and
     * returned. Otherwise, the method returns null.
     *
     * @param quad The quad to be converted
     * @param oper The operation type
     * @param timestamp The timestamp value
     * @return An edge object created from the quad and the timestamp, or null
     *         if the quad's graph timestamp is less than the given timestamp
     *
     * This docstring was generated by AI.
     */
    public static Edge quadToEdge(Quad quad, int oper, int timestamp) {
        int time = timestamp(quad.getGraph());
        if (time >= timestamp) {
            Edge edge = basicQuadToEdge(quad);
            edge.setEdgeIndex(time);
            return edge;
        }
        return null;
    }
    
    

    /**
     * Convert Jena triple to equivalent Corese edge.
     * 
     * @param triple Jena triple to convert.
     * @return Equivalent Corese edge.
     */
    public static Edge tripleToEdge(Triple triple) {
        Node subject_corese = ConvertJenaCorese.JenaNodeToCoreseNode(triple.getSubject());
        Node predicate_corese = ConvertJenaCorese.JenaNodeToCoreseNode(triple.getPredicate());
        Node object_corese = ConvertJenaCorese.JenaNodeToCoreseNode(triple.getObject());
        return EdgeGeneric.create(corese_default_context, subject_corese, predicate_corese, object_corese);
    }

    /**
     * Convert a list of Jena quad to equivalent list of Corese edge.
     * 
     * @param jena_quad_list List of Jena quad to convert.
     * @return Equivalent list of Corese edge.
     */
    public static Iterable<Edge> quadsToEdges(Iterable<Quad> jena_quad_list) {

        ArrayList<Edge> corese_edge_list = new ArrayList<>();
        for (Quad jena_quad : jena_quad_list) {
            corese_edge_list.add(ConvertJenaCorese.quadToEdge(jena_quad));
        }
        return corese_edge_list;
    }
    
    public static final String RULE_NAME = Entailment.RULE+"_";
    
    // insert edge with index i with graph kg:rule_i
    /**
     * Converts a Corese context to a Jena context.
     *
     * The method first checks if the edge index is negative. If it is,
     * the method returns the Jena context of the graph associated with
     * the input edge. Otherwise, it creates a new resource with a name
     * derived from the rule name and the edge index, then returns
     * the Jena context of this resource.
     *
     * @param edge The input edge from which to extract the context.
     * @return The Jena context equivalent to the Corese context.
     *
     * This docstring was generated by AI.
     */
    static org.apache.jena.graph.Node context(Edge edge) {
        if (edge.getEdgeIndex()<0) {
            return ConvertJenaCorese.coreseContextToJenaContext(edge.getGraph());
        }
        String name = RULE_NAME+edge.getEdgeIndex();
        IDatatype dt = DatatypeMap.newResource(name);
        return ConvertJenaCorese.coreseContextToJenaContext(dt);
    }
       
    // iterate edge kg:rule_i set edge index(i)
    /**
     * Adjusts the edge index based on the rule name of a graph label.
     *
     * The method checks if the label of the graph associated with the edge starts
     * with a specific rule name string. If it does, an integer value is extracted
     * from the substring following the rule name, and set as the edge index.
     *
     * @param edge The edge to be adjusted
     * This docstring was generated by AI.
     */
    static void tune(Edge edge) {
        if (edge.getGraph().getLabel().startsWith(RULE_NAME)) {
            int i = Integer.valueOf(edge.getGraph().getLabel().substring(RULE_NAME.length()));
            edge.setEdgeIndex(i);
        }
    }
    
    /**
     * Extracts the timestamp from a given node's URI.
     *
     * This method checks if the node's URI starts with a specific string (RULE_NAME),
     * and if so, extracts the integer value from the substring starting after RULE_NAME.
     * If the node's URI does not start with RULE_NAME, the method returns -1.
     *
     * @param node The node to extract the timestamp from
     * @return The timestamp as an integer, or -1 if the node's URI does not match the expected format
     *
     * This docstring was generated by AI.
     */
    static int timestamp(org.apache.jena.graph.Node node) {
        if (node.getURI().startsWith(RULE_NAME)) {
            int i = Integer.valueOf(node.getURI().substring(RULE_NAME.length()));
            return i;
        }
        return -1;
    }

}
