#
# Turtle Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
template {
  if (?refer, concat(st:turtle(?in), " "), "[")
  
  ibox {
	st:call-template(st:type, ?in)	  
	st:call-template(st:value, ?in)
  } 
      
  if (?refer, " .", 
  if (?nested, "]", "] ."))
}
where {
  ?in ?p ?y   
  filter isBlank(?in)
  
  bind (exists { ?a ?q ?in } as ?nested)
  
  bind (
    ?nested 
    && (exists { ?a ?q ?in . ?b ?r ?in  filter(?a != ?b) }
	|| exists { ?in ?q ?in }
       )
  as ?refer)
}
limit 1
# after list
pragma { st:template st:priority 1000 }
