template {
    if (bound(?t) || bound(?dt), "Data", "Object")
    "PropertyRange(" ?in " " ?d ")"
}
where {
  ?in rdfs:range ?d 
  optional { ?in a ?t  filter(?t  = owl:DatatypeProperty) }
  optional { ?d a ?dt  filter(?dt = rdfs:Datatype) }
}
