template {
   xsd:string(?l) "(" ?in " " ?p ")"
}
where {
  ?in rdfs:subPropertyOf ?p 
  optional { ?in a ?t }
  optional  { ?p a ?t }
  filter (?t = ?tt)
}
values (?tt ?l){ 
  (owl:ObjectProperty   "SubObjectPropertyOf")
  (owl:DatatypeProperty "SubDataPropertyOf" )
}