# SHACL Interpreter
 
#@public @import <http://ns.inria.fr/sparql-template/function/datashape/main.rq>
template {
   xt:size(?g)
}
where {
   #bind (sh:trace(true) as ?d)
   #bind (sh:shaclshape(shapeNode) as ?g)
   #bind (sh:shaclshape(shapeNode, targetNode) as ?g)
   #bind (sh:shaclnode(targetNode) as ?g)
   #bind (sh:setup(sh:callback, us:callback) as ?b1)
   bind (sh:fast(true) as ?f)
   bind (sh:shacl() as ?g)

}
