#
# Display connection history as map and charts
# History recorded by server EventManager in ldscript static variable ?staticEventManagerMap 
# Functions defined in corese core function/logger.rq
#
# use case: http://localhost:8080/srv/service/log
#
template st:start {
   "<h2>Server Log</h2>"
   
   st:call-template(st:map,   ?jsonlist)
   st:call-template(st:chart, ?jsonlist, "country")
   #st:call-template(st:chart, ?jsonlist, "org")
}
where {
    # list of json descriptions of IP address
    bind (us:jsonlist() as ?jsonlist)
}

