#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  st:kw("bind") " (" ?e " " 
  st:kw("as") " " ?v ")"
}
where {
  ?in a sp:Bind  ;
      sp:expression ?e ;
      sp:variable ?v
}



