#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  ?e " " st:kw( str(?l)) " ("     
     st:call-template(sp:argin, ?in)
  ")"
}
where {
  ?in a ?t ; sp:arg1 ?e
}
values (?t ?l) {
  (sp:in "in")
  (sp:IN "in")
  (sp:notIn "not in")
}



