#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template sp:named {
   st:kw( "from named")
   " " ?f st:nl() 
   
   ; separator = ""
}
where {
  ?in sp:fromNamed ?l
  ?l rdf:rest*/rdf:first ?f
}



