#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template st:main {

   st:call-template-with(st:spin, st:mode, st:html)

}
where {
}



