#
# Query Service HTTP Header RDF graph
#
prefix ns: <http://ns.inria.fr/corese/log/>
prefix hd: <http://ns.inria.fr/corese/log/header/>

select ?url ?serv ?out ?p ?o 
where {
    ?s ?p ?o ;
        ns:endpointNumber ?n ;
        ns:endpointURL ?url 
        filter strstarts(?p, hd:)
        optional { ?s hd:Server ?serv }
        optional { ?s ns:outputCard ?out }
}
order by ?n ?s ?p ?o
