#
# Listen Corese activity
#
# @federate <http://localhost:8080/sparql>
select where {}

function xt:main() {
   xt:tune(xt:listen, true)
}

function xt:insert(?t){
  xt:display(?t)
}

function xt:delete(?t){
  xt:display(?t)
}

function xt:load(?p){
  xt:display(?p)
}

function xt:begin(?q, ?ast){
  xt:display(?ast)
}

function xt:end(?q, ?ast, ?ms){
  xt:display(?ms)
}
