template {
    xsd:string(?l) "("  ?in " "  ?p ")"   
}
where {
  ?in owl:propertyDisjointWith ?p 
  optional { ?in a ?t }
  optional  { ?p a ?t }
  filter (?t = ?tt)
}
values (?tt ?l) {
  (owl:ObjectProperty   "DisjointObjectProperties")
  (owl:DatatypeProperty "DisjointDataProperties")
}
