template {
    if (?dp, "DisjointDataProperties", "DisjointObjectProperties") 
    "("  ?l ")"   
}
where {
  ?in a owl:AllDisjointProperties ;
    owl:members ?l 
    
    bind( 
    exists {
      ?l rdf:rest*/rdf:first ?p 
      ?p a owl:DatatypeProperty
    } 
    as ?dp)
}
