prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {
    ?sh sh:class ?c 
  }
  
  values ?o { unnest(sh:path(?shape, ?s, ?p)) }
  bind (exists { ?o rdf:type/rdfs:subClassOf* ?c } as ?suc)

  bind (st:report(sh:class, ?sh, ?shape, ?s, ?s, ?p, ?o, ?suc, ?vis) as ?b)
}

