prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {
    ?sh sh:lessThan|sh:lessThanOrEquals ?q ; ?r ?q  
  }
  
  ?s ?p ?o ; ?q ?v
  
  bind (coalesce(if (?r = sh:lessThan, ?o < ?v, ?o <= ?v), false) as ?suc)
    
  bind (st:report(?r, ?sh, ?shape, ?s, ?s, ?q, ?o, ?suc, ?vis) as ?b)
  
}
 
