prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {
    ?sh sh:nodeKind ?k  
  }
  
  values ?o { unnest(sh:path(?shape, ?s, ?p)) }
  bind (sh:hasKind(?o, ?k)  as ?suc)

  bind (st:report(sh:nodeKind, ?sh, ?shape, ?s, ?s, ?p, ?o, ?suc, ?vis) as ?b)
}

