prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:not (?shape, ?sh, ?vis, ?s, ?p, ?cst, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {
  values ?o { unnest(sh:path(?shape, ?s, ?p)) }

  bind (! sh:hasPath(?shape, ?cst, false, ?s, ?p, ?o) as ?suc)
  
  bind (st:report(sh:shape, ?sh, ?shape, ?s, ?suc, ?vis) as ?b)
}
