prefix sh:  <http://www.w3.org/ns/shacl#> 
prefix fun:  <http://www.w3.org/ns/shacl#> 
prefix java: <function://fr.inria.corese.extension.DataShape>  

template sh:or (?shape, ?sh, ?vis, ?s, ?p, ?or, ?o) {
    sh:safe(?shape, ?sh, ?suc)
}
where {
  
    values ?o { unnest(java:path(?shape, ?s, ?p)) }
    
    bind (java:or(?or, ?s, ?p, ?o, ?shape) as ?count)
	bind (! bound(?count) AS ?failure) .
	bind ( IF (?failure, false, ?count)  as ?suc)

    bind (java:report(sh:or, ?sh, ?shape, ?s, ?p, ?o, ?suc, ?vis) as ?b)
  
}


