prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {  
    ?sh sh:shape ?cst  
  }
  
  values ?o { unnest(sh:path(?shape, ?s, ?p)) }
  
  bind (sh:testShape(?shape, ?cst, ?o) as ?suc)
  bind (st:report(sh:shape, ?sh, ?shape, ?s, ?s, ?p, ?o, ?suc, ?vis) as ?b)
}
