prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {
    ?sh sh:uniqueLang ?l  
  }
   
  bind (sh:path(?shape, ?s, ?p) as ?values)
  values ?o { unnest(?values) }
  
  bind (lang(?o) as ?lang)
  filter (bound(?lang) && ?lang != "")
  
  bind (! mapfind(sh:sameLang, ?o, ?values) as ?suc)
  
  bind (st:report(sh:uniqueLang, ?sh, ?shape, ?s, ?s, ?p, ?o, ?suc, ?vis) as ?b)
}


function sh:sameLang(?x, ?y){
    isLiteral(?y) && datatype(?y) = rdf:langString && lang(?y) = lang(?x) && ?x != ?y
}
