prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:uniqueLang (?shape, ?sh, ?vis, ?s, ?p, ?l, ?o){
    let (?suc = false, ?b = st:report(sh:uniqueLang, ?sh, ?shape, ?s, ?p, ?lang, ?suc, ?vis)){
        sh:safe(?shape, ?sh, ?suc)
    } 
}
where {

    select ?shape ?s ?p ?lang (count(?val) as ?c)  
    where {
        values ?val { unnest(sh:path(?shape, ?s, ?p)) }
        bind (lang(?val) as ?lang)
        filter (bound(?lang) && ?lang != "")
    } 
    group by ?lang
    having (?c > 1)
    
}


