template st:propertyvalue(?x, ?p) {

     '"' 
     if (?p = rdf:type,
     '@type',
     st:turtle(?p, true))
     
     '": '   
     
    if (?mult, "[", "") 
    
    group { 
    
     if (?p = rdf:type, 
       st:turtle(str(?y)),
       st:apply-templates-with(st:jsonterm, ?y))  
      
      ; separator = ", "
      
    } 
    
    if (?mult, "]", "") 
          
}
where {

  {select ?x ?p (count(*) as ?c) where { ?x ?p ?y }}
  
  bind (?c > 1 as ?mult)
  
  ?x ?p ?y  
}
order by ?y
