template  {

  "{"
    "\"@value\": \""       us:escape(?in) "\", "
    "\"@language\": \""    lang(?in) "\""
  "}"
  
}
where {
  bind (st:getFocusNode() as ?in)
  filter (datatype(?in) = rdf:langString)
  
}
