template  {

  "{"
    "\"@value\": \""   us:escape(?in) "\", "
    "\"@type\": \""    datatype(?in) "\""
  "}"
  
}
where {
  bind (st:getFocusNode() as ?in)
  filter (
    ! strstarts(datatype(?in), xsd:) &&
    ! strstarts(datatype(?in), rdf:) 
  )
  
}
