/* Generated By:JavaCC: Do not edit this line. SparqlCoreseConstants.java */
package fr.inria.acacia.corese.triple.javacc1;

public interface SparqlCoreseConstants {

  int EOF = 0;
  int WS = 6;
  int SINGLE_LINE_COMMENT = 7;
  int Q_IRIref = 8;
  int QNAME_NS = 9;
  int QNAME = 10;
  int BLANK_NODE_LABEL = 11;
  int VAR1 = 12;
  int VAR2 = 13;
  int ABASE = 14;
  int APREFIX = 15;
  int LANGTAG = 16;
  int A2Z = 17;
  int A2ZN = 18;
  int KW_A = 19;
  int INV = 20;
  int SHORT = 21;
  int SHORTALL = 22;
  int DEPTH = 23;
  int BREADTH = 24;
  int BASE = 25;
  int PREFIX = 26;
  int SELECT = 27;
  int DESCRIBE = 28;
  int CONSTRUCT = 29;
  int RULE = 30;
  int ASK = 31;
  int DISTINCT = 32;
  int SEPARATOR = 33;
  int REDUCED = 34;
  int LIMIT = 35;
  int OFFSET = 36;
  int ORDER = 37;
  int BY = 38;
  int ANY = 39;
  int RELAX = 40;
  int ASC = 41;
  int DESC = 42;
  int NAMED = 43;
  int FROM = 44;
  int WHERE = 45;
  int AND = 46;
  int GRAPH = 47;
  int SERVICE = 48;
  int REC = 49;
  int STATE = 50;
  int LEAF = 51;
  int OPTIONAL = 52;
  int UNION = 53;
  int MINUSP = 54;
  int NOT = 55;
  int SCOPE = 56;
  int FORALL = 57;
  int IF = 58;
  int THEN = 59;
  int ELSE = 60;
  int EXIST = 61;
  int FILTER = 62;
  int LOAD = 63;
  int CLEAR = 64;
  int DROP = 65;
  int CREATE = 66;
  int ADD = 67;
  int TO = 68;
  int MOVE = 69;
  int COPY = 70;
  int INSERT = 71;
  int DELETE = 72;
  int WITH = 73;
  int USING = 74;
  int DEFAUT = 75;
  int ALL = 76;
  int INTO = 77;
  int SILENT = 78;
  int DATA = 79;
  int BOUND = 80;
  int STR = 81;
  int DTYPE = 82;
  int LANG = 83;
  int LANGMATCHES = 84;
  int IS_URI = 85;
  int IS_IRI = 86;
  int IS_BLANK = 87;
  int IS_LITERAL = 88;
  int REGEX = 89;
  int TRUE = 90;
  int FALSE = 91;
  int ONE = 92;
  int S_MORE = 93;
  int LIST = 94;
  int MERGE = 95;
  int DISPLAY = 96;
  int PRAGMA = 97;
  int D_RDF = 98;
  int D_JSON = 99;
  int D_FLAT = 100;
  int D_ASQUERY = 101;
  int D_XML = 102;
  int D_BLANK = 103;
  int THRESHOLD = 104;
  int RESULT = 105;
  int PROJECTION = 106;
  int GROUP = 107;
  int HAVING = 108;
  int BINDINGS = 109;
  int VALUES = 110;
  int BIND = 111;
  int UNDEF = 112;
  int COUNT = 113;
  int SOURCE = 114;
  int SCORE = 115;
  int AS = 116;
  int SORT = 117;
  int REVERSE = 118;
  int OR = 119;
  int OPTION = 120;
  int SORTED = 121;
  int ALL2 = 122;
  int CURRENT = 123;
  int ONE2 = 124;
  int DIRECT2 = 125;
  int COLON2 = 126;
  int DISTANCE = 127;
  int DEBUG = 128;
  int CHECK = 129;
  int NOSORT = 130;
  int TUPLE = 131;
  int XPATH = 132;
  int IN = 133;
  int EQ2 = 134;
  int NE2 = 135;
  int BEGIN_WITH = 136;
  int STRICT_SPEC = 137;
  int SPEC = 138;
  int SAME = 139;
  int GENERALISATION = 140;
  int STRICT_GENERALISATION = 141;
  int EQ_LANG = 142;
  int SIMPLE_STRING = 143;
  int INTEGER = 144;
  int DECIMAL = 145;
  int DOUBLE = 146;
  int EXPONENT = 147;
  int QUOTE_3D = 148;
  int QUOTE_3S = 149;
  int ECHAR = 150;
  int STRING_LITERAL1 = 151;
  int STRING_LITERAL2 = 152;
  int STRING_LITERAL_LONG1 = 153;
  int STRING_LITERAL_LONG2 = 154;
  int DIGITS = 155;
  int HEX = 156;
  int LPAREN = 157;
  int RPAREN = 158;
  int LBRACE = 159;
  int RBRACE = 160;
  int LBRACKET = 161;
  int RBRACKET = 162;
  int ANON = 163;
  int SEMICOLON = 164;
  int COMMA = 165;
  int DOT = 166;
  int EQ = 167;
  int NE = 168;
  int GT = 169;
  int LT = 170;
  int LE = 171;
  int GE = 172;
  int BANG = 173;
  int TILDE = 174;
  int COLON = 175;
  int SC_OR = 176;
  int SC_AND = 177;
  int PLUS = 178;
  int MINUS = 179;
  int STAR = 180;
  int SLASH = 181;
  int QM = 182;
  int BAR = 183;
  int DATATYPE = 184;
  int AT = 185;
  int NCCHAR1p = 186;
  int NCCHAR1 = 187;
  int NCCHAR = 188;
  int NCNAME_PREFIX = 189;
  int NCNAME = 190;
  int BLANKNAME = 191;
  int VARNAME = 192;
  int LOCAL_ESC = 193;
  int PERCENT = 194;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<Q_IRIref>",
    "<QNAME_NS>",
    "<QNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "\"@base\"",
    "\"@prefix\"",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"i\"",
    "\"s\"",
    "<SHORTALL>",
    "\"d\"",
    "\"b\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"describe\"",
    "\"construct\"",
    "\"rule\"",
    "\"ask\"",
    "\"distinct\"",
    "\"separator\"",
    "\"reduced\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"any\"",
    "\"relax\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"service\"",
    "\"rec\"",
    "\"state\"",
    "\"leaf\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"not\"",
    "\"scope\"",
    "\"forall\"",
    "\"iff\"",
    "\"then\"",
    "\"else\"",
    "\"exists\"",
    "\"filter\"",
    "\"load\"",
    "\"clear\"",
    "\"drop\"",
    "\"create\"",
    "\"add\"",
    "\"to\"",
    "\"move\"",
    "\"copy\"",
    "\"insert\"",
    "\"delete\"",
    "\"with\"",
    "\"using\"",
    "\"default\"",
    "\"all\"",
    "\"into\"",
    "\"silent\"",
    "\"data\"",
    "\"bound\"",
    "\"str\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"true\"",
    "\"false\"",
    "\"one\"",
    "\"more\"",
    "\"list\"",
    "\"merge\"",
    "\"display\"",
    "\"pragma\"",
    "\"rdf\"",
    "\"json\"",
    "\"flat\"",
    "\"asquery\"",
    "\"xml\"",
    "\"blank\"",
    "\"threshold\"",
    "\"result\"",
    "\"projection\"",
    "\"group\"",
    "\"having\"",
    "\"bindings\"",
    "\"values\"",
    "\"bind\"",
    "\"undef\"",
    "\"count\"",
    "\"source\"",
    "\"score\"",
    "\"as\"",
    "\"sort\"",
    "\"reverse\"",
    "\"or\"",
    "\"option\"",
    "\"sorted\"",
    "\"all::\"",
    "\"current::\"",
    "\"one::\"",
    "\"direct::\"",
    "\"::\"",
    "\"distance\"",
    "\"debug\"",
    "\"check\"",
    "\"nosort\"",
    "\"tuple\"",
    "\"xpath\"",
    "\"in\"",
    "\"==\"",
    "\"!==\"",
    "\"^\"",
    "\"<:\"",
    "\"<=:\"",
    "\"=:\"",
    "\">=:\"",
    "\">:\"",
    "\"~=\"",
    "<SIMPLE_STRING>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<HEX>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"?\"",
    "\"|\"",
    "\"^^\"",
    "\"@\"",
    "<NCCHAR1p>",
    "<NCCHAR1>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<BLANKNAME>",
    "<VARNAME>",
    "<LOCAL_ESC>",
    "<PERCENT>",
  };

}
