/* Generated By:JavaCC: Do not edit this line. SparqlCoreseConstants.java */
package fr.inria.acacia.corese.triple.javacc1;

public interface SparqlCoreseConstants {

  int EOF = 0;
  int WS = 6;
  int SINGLE_LINE_COMMENT = 7;
  int Q_IRIref = 8;
  int QNAME_NS = 9;
  int QNAME = 10;
  int BLANK_NODE_LABEL = 11;
  int VAR1 = 12;
  int VAR2 = 13;
  int ABASE = 14;
  int APREFIX = 15;
  int ATLIST = 16;
  int ATPATH = 17;
  int ATEXPORT = 18;
  int ATPUBLIC = 19;
  int ATTRACE = 20;
  int ATDEBUG = 21;
  int ATMORE = 22;
  int ATRELAX = 23;
  int ATTEST = 24;
  int ATSERVICE = 25;
  int ATDISPLAY = 26;
  int ATIMPORT = 27;
  int LANGTAG = 28;
  int A2Z = 29;
  int A2ZN = 30;
  int KW_A = 31;
  int INV = 32;
  int SHORT = 33;
  int SHORTALL = 34;
  int DEPTH = 35;
  int BREADTH = 36;
  int LIST = 37;
  int BASE = 38;
  int PREFIX = 39;
  int SELECT = 40;
  int DESCRIBE = 41;
  int CONSTRUCT = 42;
  int RULE = 43;
  int ASK = 44;
  int TEMPLATE = 45;
  int DISTINCT = 46;
  int SEPARATOR = 47;
  int REDUCED = 48;
  int LIMIT = 49;
  int OFFSET = 50;
  int ORDER = 51;
  int BY = 52;
  int RELAX = 53;
  int ASC = 54;
  int DESC = 55;
  int NAMED = 56;
  int FROM = 57;
  int WHERE = 58;
  int AND = 59;
  int GRAPH = 60;
  int SERVICE = 61;
  int REC = 62;
  int STATE = 63;
  int LEAF = 64;
  int OPTIONAL = 65;
  int UNION = 66;
  int MINUSP = 67;
  int NOT = 68;
  int SCOPE = 69;
  int LET = 70;
  int SET = 71;
  int FOR = 72;
  int IF = 73;
  int THEN = 74;
  int ELSE = 75;
  int EXIST = 76;
  int FILTER = 77;
  int LOAD = 78;
  int CLEAR = 79;
  int DROP = 80;
  int CREATE = 81;
  int ADD = 82;
  int TO = 83;
  int MOVE = 84;
  int COPY = 85;
  int INSERT = 86;
  int DELETE = 87;
  int WITH = 88;
  int USING = 89;
  int DEFAUT = 90;
  int ALL = 91;
  int INTO = 92;
  int SILENT = 93;
  int DATA = 94;
  int BOUND = 95;
  int STR = 96;
  int DTYPE = 97;
  int LANG = 98;
  int LANGMATCHES = 99;
  int IS_URI = 100;
  int IS_IRI = 101;
  int IS_BLANK = 102;
  int IS_LITERAL = 103;
  int REGEX = 104;
  int TRUE = 105;
  int FALSE = 106;
  int ONE = 107;
  int S_MORE = 108;
  int MERGE = 109;
  int DISPLAY = 110;
  int PRAGMA = 111;
  int D_RDF = 112;
  int D_JSON = 113;
  int D_FLAT = 114;
  int D_ASQUERY = 115;
  int D_XML = 116;
  int D_BLANK = 117;
  int THRESHOLD = 118;
  int RESULT = 119;
  int PROJECTION = 120;
  int GROUP = 121;
  int FORMAT = 122;
  int BOX = 123;
  int IBOX = 124;
  int SBOX = 125;
  int HAVING = 126;
  int VALUES = 127;
  int BIND = 128;
  int UNDEF = 129;
  int COUNT = 130;
  int SOURCE = 131;
  int SCORE = 132;
  int AS = 133;
  int SORT = 134;
  int REVERSE = 135;
  int OR = 136;
  int OPTION = 137;
  int SORTED = 138;
  int ALL2 = 139;
  int CURRENT = 140;
  int ONE2 = 141;
  int DIRECT2 = 142;
  int COLON2 = 143;
  int DISTANCE = 144;
  int DEBUG = 145;
  int CHECK = 146;
  int NOSORT = 147;
  int TUPLE = 148;
  int XPATH = 149;
  int FUNCTION = 150;
  int EXPORT = 151;
  int PACKAGE = 152;
  int IN = 153;
  int EQ2 = 154;
  int NE2 = 155;
  int BEGIN_WITH = 156;
  int STRICT_SPEC = 157;
  int SPEC = 158;
  int SAME = 159;
  int GENERALISATION = 160;
  int STRICT_GENERALISATION = 161;
  int EQ_LANG = 162;
  int SIMPLE_STRING = 163;
  int INTEGER = 164;
  int DECIMAL = 165;
  int DOUBLE = 166;
  int EXPONENT = 167;
  int QUOTE_3D = 168;
  int QUOTE_3S = 169;
  int ECHAR = 170;
  int STRING_LITERAL1 = 171;
  int STRING_LITERAL2 = 172;
  int STRING_LITERAL_LONG1 = 173;
  int STRING_LITERAL_LONG2 = 174;
  int DIGITS = 175;
  int HEX = 176;
  int LPAREN = 177;
  int RPAREN = 178;
  int LBRACE = 179;
  int RBRACE = 180;
  int LBRACKET = 181;
  int RBRACKET = 182;
  int ANON = 183;
  int SEMICOLON = 184;
  int COMMA = 185;
  int DOT = 186;
  int EQ = 187;
  int NE = 188;
  int GT = 189;
  int LT = 190;
  int LE = 191;
  int GE = 192;
  int BANG = 193;
  int TILDE = 194;
  int COLON = 195;
  int SC_OR = 196;
  int SC_AND = 197;
  int PLUS = 198;
  int MINUS = 199;
  int STAR = 200;
  int SLASH = 201;
  int QM = 202;
  int BAR = 203;
  int DATATYPE = 204;
  int AT = 205;
  int NCCHAR1p = 206;
  int NCCHAR1 = 207;
  int NCCHAR = 208;
  int NCNAME_PREFIX = 209;
  int NCNAME = 210;
  int BLANKNAME = 211;
  int VARNAME = 212;
  int LOCAL_ESC = 213;
  int PERCENT = 214;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<Q_IRIref>",
    "<QNAME_NS>",
    "<QNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "\"@base\"",
    "\"@prefix\"",
    "\"@list\"",
    "\"@path\"",
    "\"@export\"",
    "\"@public\"",
    "\"@trace\"",
    "\"@debug\"",
    "\"@more\"",
    "\"@relax\"",
    "\"@test\"",
    "\"@service\"",
    "\"@display\"",
    "\"@import\"",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"i\"",
    "\"s\"",
    "<SHORTALL>",
    "\"d\"",
    "\"b\"",
    "\"list\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"describe\"",
    "\"construct\"",
    "\"rule\"",
    "\"ask\"",
    "\"template\"",
    "\"distinct\"",
    "\"separator\"",
    "\"reduced\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"relax\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"service\"",
    "\"rec\"",
    "\"state\"",
    "\"leaf\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"not\"",
    "\"scope\"",
    "\"let\"",
    "\"set\"",
    "\"for\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"exists\"",
    "\"filter\"",
    "\"load\"",
    "\"clear\"",
    "\"drop\"",
    "\"create\"",
    "\"add\"",
    "\"to\"",
    "\"move\"",
    "\"copy\"",
    "\"insert\"",
    "\"delete\"",
    "\"with\"",
    "\"using\"",
    "\"default\"",
    "\"all\"",
    "\"into\"",
    "\"silent\"",
    "\"data\"",
    "\"bound\"",
    "\"str\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"true\"",
    "\"false\"",
    "\"one\"",
    "\"more\"",
    "\"merge\"",
    "\"display\"",
    "\"pragma\"",
    "\"rdf\"",
    "\"json\"",
    "\"flat\"",
    "\"asquery\"",
    "\"xml\"",
    "\"blank\"",
    "\"threshold\"",
    "\"result\"",
    "\"projection\"",
    "\"group\"",
    "\"format\"",
    "\"box\"",
    "\"ibox\"",
    "\"sbox\"",
    "\"having\"",
    "\"values\"",
    "\"bind\"",
    "\"undef\"",
    "\"count\"",
    "\"source\"",
    "\"score\"",
    "\"as\"",
    "\"sort\"",
    "\"reverse\"",
    "\"or\"",
    "\"option\"",
    "\"sorted\"",
    "\"all::\"",
    "\"current::\"",
    "\"one::\"",
    "\"direct::\"",
    "\"::\"",
    "\"distance\"",
    "\"debug\"",
    "\"check\"",
    "\"nosort\"",
    "\"tuple\"",
    "\"xpath\"",
    "\"function\"",
    "\"export\"",
    "\"package\"",
    "\"in\"",
    "\"==\"",
    "\"!==\"",
    "\"^\"",
    "\"<:\"",
    "\"<=:\"",
    "\"=:\"",
    "\">=:\"",
    "\">:\"",
    "\"~=\"",
    "<SIMPLE_STRING>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<HEX>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"?\"",
    "\"|\"",
    "\"^^\"",
    "\"@\"",
    "<NCCHAR1p>",
    "<NCCHAR1>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<BLANKNAME>",
    "<VARNAME>",
    "<LOCAL_ESC>",
    "<PERCENT>",
  };

}
