#
# defaut processing of a variable 
#
# Olivier Corby, Wimmics Inria I3S, 2014
#
template st:profile(?in) {    
    
}
where {}

function st:process(?in) { st:turtle(?in) }
     
function st:default(?in) { st:turtle(?in) }

