#
# Generate a form with a SPARQL query ?q to submit
# Argument  ?n is the name of query (st:minus)
# ?q actual query, ?t query template, ?s query solution
#
prefix ft: <http://ns.inria.fr/sparql-template/format/tutorial/>
template st:form(?n, ?q, ?t, ?s, ?qt) {
   
   format {   
    ft:form.html
   
    st:get(st:service) 
    st:get(st:profile)
    str(?t) 
    str(?s) 
    ?n 
    if (?s = st:null, "", st:format(ft:nav.html))
    st:call-template(st:selecttable, ?n, ?q, ?t, ?s, ?qt)
    st:call-template(st:selectsilent,?n, ?q, ?t, ?s, ?qt)
    str(?q)
    }
   
}
where {
    bind (st:get(st:context) as ?g)
    graph ?g {  
        ?qt st:name ?n 
    }
}
