#
# Generate param selector, ?n = query name  
#
prefix ft: <http://ns.inria.fr/sparql-template/format/tutorial/>
template st:selectparam(?n, ?select) {

format {
  ft:selectparam.html 
  ?name
  group { 
    format { 
        if (st:get(?uri, ?value), 
            '<option value="%s" selected="true">%s</option>', 
            '<option value="%s">%s</option>')
            
        ?value ?value
    } 
}
}
   
}
where {
  bind (st:get(st:context) as ?g)
  
  graph ?g {
    ?select st:name ?name ; st:uri ?uri ;
       st:value/rdf:rest*/rdf:first ?value      
  }
}
