#
# Generate a form with a SPARQL query ?q to submit
# Argument  ?n is the name of query (st:minus)
# ?q actual query, ?t query template, ?s query solution
#
prefix ft: <http://ns.inria.fr/sparql-template/format/tutorial/>
template st:selecttable(?n, ?q, ?t, ?s, ?qt) {
   
   format { 
        "<table>%s</table>"
        group { st:call-template(st:selectparam2, ?n, ?select) }
   }
   
      
}
where {
    bind (st:get(st:context) as ?g)
    graph ?g {  
        ?qt st:name ?n 
        optional { ?qt st:select ?select }
    }
}
