template st:pagecons {
   format {
    us:format("construct.html")
    st:call-template(st:tablecons)
    format {
      us:format("d3graph.html")
      st:apply-templates-with(st:d3)
   }
   }
}
where {
}


# utiliser prefix ft: <http:.... navlab> (cf display.rq dans navlab) et utiliser ft:link.html
