prefix rs: <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>
prefix ft: <http://ns.inria.fr/sparql-template/format/sparql/>

template st:pageask {
format {
  ft:ask.html
  ?b
}
}
where {
  ?r rs:boolean ?b
}
