prefix ft: <http://ns.inria.fr/sparql-template/format/sparql/>
template st:pagecons {
   format {
    ft:construct.html
    st:call-template(st:tablecons)
    st:apply-templates-with(st:d3)
   }
}
where {
}


