prefix ft: <http://ns.inria.fr/sparql-template/format/sparql/>
template st:pageselect {
    format {
        ft:select.html
        st:call-template(st:variable)
        st:call-template(st:table)
    }    
}
where {
}
