prefix rs: <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>
prefix ft: <http://ns.inria.fr/sparql-template/format/sparql/>
template  {

format { 
    ft:value.html     
    coalesce(st:display(?val), "&nbsp;")
}  
; separator = " "

}
where {
  ?x rs:solution ?in
  ?x rs:resultVariable ?var 
  
  optional {
    ?in rs:binding [ rs:variable ?var ; rs:value ?val ]
  }
  
}
order by ?var
