prefix ft: <http://ns.inria.fr/sparql-template/format/sparql/>
template st:tableconsuri {

 format {
        ft:triple.html
        
        st:number()
        st:call-template(st:show,    ?x)
        st:display(?x) 
        st:display(?p) 
        st:display(?y) 
        st:call-template(st:show,    ?y)
    }
}
where {
  bind (st:focus() as ?uri)
  ?x ?p ?y
  filter (?uri in (?x, ?p, ?y))
}
order by ?x ?p ?y


