#
# Generate a form with a SPARQL query ?q to submit
# Argument  ?n is the name of query (st:minus)
# ?q actual query, ?t query template, ?s query solution
#
template st:form(?n, ?q, ?t, ?s) {
  """
   <script type="text/javascript">           
        function show(name){
            document.getElementById('query').value = document.getElementById(name).value;
        }
   </script>
       
   <form method='post'  action='' >   
   <input type='hidden' id='tmp' value='"""str(?t)"""' />
   <input type='hidden' id='sol' value='"""str(?s)"""' />
   <input type='hidden' name='uri' value='""" ?n """'/>
   <input type='hidden' name='profile' value='""" st:get(st:profile) """'/> 
   """
   
   if (?s = st:null, "", 
   """<input type='button' onclick="show('sol')" value='Solution' />
      <input type='button' onclick="show('tmp')" value='Template' /> 
   """)
   
   """
   <input type='submit' value='Submit' />
   <br/>
   <textarea cols='60' rows='10' id='query' name='query'>"""str(?q)"""</textarea>
   </form>
  """
}
where {

}