template st:next(?t) {

  "<a  href='" st:plink(?n) "'>"
  "<button type='button'"  st:call-template-with(st:server, st:bstyle)
  ">Next</button>"
  "</a>"  
    
}
where {
  bind (st:get(st:context) as ?g)
  
  graph ?g {
    ?q1 st:name ?t ; st:index ?i
    bind (?i + 1 as ?j)
    ?q2 st:index ?j ;
	st:name ?n 
  }
}
