template st:prev(?t) {

format {
  """
  <a  href='%s'>
  <button type='button' %s>Previous</button>
  </a>
  """
  
  st:plink(?n)
  st:bstyle()
  }
  
}
where {
  bind (st:get(st:context) as ?g)
  
  graph ?g {
    ?q1 st:name ?t ; st:index ?i
    bind (?i - 1 as ?j)
    ?q2 st:index ?j ;
	st:name ?n 
  }
}
