template st:script {
   """
   <script type="text/javascript">           
        function show(name){
            document.getElementById('query').value = document.getElementById(name).value;
        }                
   </script>
   """
}
where {}