#
# Select a query name to display and execute
# query name bound to uri param
# Generate query names list from context graph
#
template st:select(?t) {

"""
<h3>Select a query</h3>

<form method='get' id ='select' action='""" st:get(st:service) """'>

  <input type='hidden' name='profile' value='""" st:get(st:profile) """' />
"""

  st:call-template(st:prev, ?t)

  "<select " st:call-template-with(st:server, st:sstyle)   
    " id='uri' name='uri' onChange='" 
  
  if (st:get(st:protocol, st:ajax), 
    "trans(this.form); return false;",
    "submit();")
  
  "'>"
  
    st:call-template(st:list, ?t)  
    
  "</select>" 

  st:call-template(st:next, ?t)
 
""" 
</form>
"""

}
where {
}
