#
# Select a query name to display and execute
# query name bound to uri param
# Generate query names list from context graph
#
template st:selectform(?t) {

format {

  """
  <h3>Select a query</h3>
  <form method='get' id ='select' action='%s'>
  <input type='hidden' name='profile' value='%s' />
  %s   
  <select %s id='uri' name='uri' onChange='%s'>
  %s
  </select>   
  %s
  </form>
  """
  
  st:get(st:service) 
  st:get(st:profile)   
  st:call-template(st:prev, ?t)  
  st:sstyle() 
  st:change() 
  st:call-template(st:list, ?t)  
  st:call-template(st:next, ?t)
}
}
where {
}
