#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template  {
  st:prolog() 
  if (bound(?g), concat("with ", ?g, "\n"), "")
  "delete where {" 
    st:call-template(sp:listnl, ?w) 
  "}"
}
where {
  ?in a sp:DeleteWhere ;
  sp:where ?w
  optional { ?in sp:with ?g }

}