prefix dqv:     <http://www.w3.org/ns/dqv#>
prefix kgi:     <http://ns.inria.fr/kg/index#>
prefix void:    <http://rdfs.org/ns/void#>
prefix dcterms: <http://purl.org/dc/terms/>
@timeout 30000
select  *
where {

service <http://prod-dekalog.inria.fr/sparql> {
    select distinct ?serv  where {
        graph ?g {
            ?metadata dcterms:modified ?modif .
            ?metadata kgi:curated ?s .
            ?s void:sparqlEndpoint  ?serv
        }
    }
    order by ?serv
}

service ?serv {select * where {?x ?p ?o} limit 1}

}
order by ?serv
