template st:main(?in) {
    str(?mes)
}
where {
  values ?e { unnest(st:errors(?in)) }
  filter strstarts(?e, st:)
  
  bind (strafter(?e, st:) as ?str)
  bind (strbefore(?str, "/") as ?type)
  bind (strafter(?str, "/")  as ?desc)
    
values (?type ?uri) {
    ("owlel" st:mainEL)
    ("owlql" st:mainQL)
    ("owlrl" st:mainRL)
    ("owltc" st:mainOWL)
} 

 bind ( st:call-template(?uri, ?desc)  as ?res)
 bind (if (strlen(?res) = 0, ?e, ?res) as ?mes)
 #filter (strlen(?res) > 0)
}
