template st:oneEL(?tag) {

if (st:get(st:execmode, st:standalone), 
    st:format("OWL EL: Enumeration with more than one %s or %s", str(?messa), str(?messb)),
    st:format("<span class='owlel'>OWL EL: Enumeration with more than one <a href='%s'>%s</a> or <a href='%s'>%s</a></span>", 
        str(?hrefa), str(?messa), str(?hrefb), str(?messb))
)
    
#	"<span class='owlel'>OWL EL: Enumeration with more than one <a href='" str(?hrefa) "'>" str(?messa) "</a> or <a href='" str(?hrefb) "'>" str(?messb) "</a>.</span>"
	
}
where {

	bind(st:linkPro(?ida) as ?hrefa)
	bind(st:linkPro(?idb) as ?hrefb)
	
} values (?tag ?messa ?ida ?messb ?idb) {
	### classExp ###
	("one" "individual" "Class_Expressions" "literal" "Data_Ranges")
}
