#
# Timeline SPARQL Template - Olivier Corby - 2014
#
prefix cn: <http://cdn.fr/schema/>
prefix foaf: <http://xmlns.com/foaf/0.1/>

template  cn:date(?date, ?topic) {

  group { ?uri ; separator = "<br/>" } 

}
where {

 graph ?g { [] cn:topic ?topic . 
	    { ?uri cn:date ?date } union { ?uri cn:begin ?date }
	  }
 
}

