#
# Timeline SPARQL Template - Olivier Corby - 2014
#
prefix cn: <http://cdn.fr/schema/>
prefix ft: <http://ns.inria.fr/sparql-template/format/cdn/>
template cn:head(?c, ?title) {
format {

  ft:head.html
    
    str(?title)
    ?title
    "" #st:call-template(cn:icon, cn:icon)
    st:call-template(cn:index,  ?title)
    }
}
where {
}
