#
# Timeline SPARQL Template - Olivier Corby - 2014
#
prefix cn: <http://cdn.fr/schema/>
prefix ft: <http://ns.inria.fr/sparql-template/format/cdn/>
template cn:sign {

   st:call-template(cn:icon, cn:icon)
   
   format { ft:sign.html }
   
   now()
}
where {
}
