#
# Timeline SPARQL Template - Olivier Corby - 2014
#
prefix cn: <http://cdn.fr/schema/>
template st:substart(?cent) {
   
   st:call-template(cn:content, ?cent)   
        
   st:call-template(cn:sign, cn:sign)
   
}
where {
}  

