#
# Timeline SPARQL Template - Olivier Corby - 2014
#
prefix cn: <http://cdn.fr/schema/>
prefix ft: <http://ns.inria.fr/sparql-template/format/cdn/>

template cn:tail(?c, ?title) {

format {
    ft:tail.html        
    st:call-template(cn:index,  ?title)        
}
    
}
where {
}
