module fr.inria.corese.corese_core {
	exports fr.inria.corese.core.load;
	exports fr.inria.corese.core;
	exports fr.inria.corese.core.query;
	exports fr.inria.corese.core.rule;
	exports fr.inria.corese.core.workflow;
	exports fr.inria.corese.core.transform;
	exports fr.inria.corese.core.util;
	exports fr.inria.corese.core.print;
	exports fr.inria.corese.core.pipe;
	exports fr.inria.corese.core.api;
	exports fr.inria.corese.core.edge;
	exports fr.inria.corese.core.logic;
	exports fr.inria.corese.core.producer;
	requires fr.inria.corese.compiler;
	requires org.slf4j;
//	requires java.logging;
////	requires java.xml;
	requires jsonld.java;
	requires arp;
//	requires java.ws.rs;
	requires java.sql;
//	requires sesame.rio.api;
//	requires sesame.model;
//	requires commons.lang;
	requires semargl.core;
	requires semargl.rdfa;
	requires fr.inria.corese.kgram;
	requires fr.inria.corese.sparql;
	requires sesame.model;
	requires sesame.rio.api;
	requires java.ws.rs;
	requires commons.lang;
	requires java.management;
	requires jdk.management;
//    requires java.annotation;
}
