#
# Check if there is an unauthorized OWL property for superClassExpression ?in
# return false in this case, otherwise template fails (return nothing)
#
template {
  false
}
where {
    ?in ?p ?y
    
    bind (
      ?p in (rdfs:subClassOf,
        owl:intersectionOf, owl:complementOf, 
	owl:onProperty, owl:hasValue, owl:allValuesFrom, 
	owl:maxCardinality, owl:maxQualifiedCardinality, owl:onClass,
	rdf:type
	)
      as ?suc)
      	
      filter (st:visit(st:err("failSuper"), ?in, ?suc))
      filter if (us:mytrace(?suc), xt:print("error super last:", ?in, ?p, ?y), true)

      filter (! ?suc)
}
limit 1
