template st:profile {}
where {}

function us:clean(?str) {
    replace(?str, "<", "&lt;")
}

function us:sort(?p, ?v) {
    if (?p = rdf:type,          0,
    if (?p = rdfs:label,        1,
    if (strstarts(?p, rdfs:),   2, 
    if (strstarts(?p, rdf:),    3, 
    if (isLiteral(?v),          4, 5)))))
}


function us:display(?t) {
    us:clean(st:turtle(?t))
}

function us:displayInverse(?t) {
    concat("is ", us:display(?t), " of")
}
