prefix orl: </user/corby/home/AData/template/owlrl/>

template {
  st:number()
  " " 
  st:apply-templates-with(st:turtle, ?node)
  
  ; separator = "\n\n"
}
where {
     filter(st:visit(st:start, st:trace)) 
     
     filter(st:visit(st:trace, st:sub,   !true))
     filter(st:visit(st:trace, st:super, !true))
     filter(st:visit(st:trace, st:equiv, !true))
     
     filter(st:visit(st:trace, st:subClass, 	true))
     filter(st:visit(st:trace, st:equivClass, 	true))
     filter(st:visit(st:trace, st:disjointClass,	true))
     filter(st:visit(st:trace, st:individual, 	true))
     filter(st:visit(st:trace, st:domain, 	true))
     filter(st:visit(st:trace, st:key, 		true))
     filter(st:visit(st:trace, st:fail, 		true))
     
     filter(st:visit(st:trace, st:silent, true))
     
     bind (st:apply-templates-with(orl:main)
     as ?res)

     bind(kg:unnest(st:visited()) as ?node)
     
}


