//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 10:15:40 AM CEST 
//


package fr.inria.edelweiss.rif.xml.schema;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import fr.inria.edelweiss.rif.ast.Term;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2007/rif#}LISTELEMENTS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "term",
    "rest"
})
@XmlRootElement(name = "List")
public class List {

    @XmlElements({
        @XmlElement(name = "External", type = ExternalTERMType.class),
        @XmlElement(name = "Expr", type = Expr.class),
        @XmlElement(name = "List", type = List.class),
        @XmlElement(name = "Var", type = Var.class),
        @XmlElement(name = "Const", type = Const.class)
    })
    protected java.util.List<java.lang.Object> term;
    protected Rest rest;

    /**
     * Gets the value of the term property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the term property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTERM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalTERMType }
     * {@link Expr }
     * {@link List }
     * {@link Var }
     * {@link Const }
     * 
     * 
     */
    public java.util.List<java.lang.Object> getTERM() {
        if (term == null) {
            term = new ArrayList<java.lang.Object>();
        }
        return this.term;
    }

    /**
     * Gets the value of the rest property.
     * 
     * @return
     *     possible object is
     *     {@link Rest }
     *     
     */
    public Rest getRest() {
        return rest;
    }

    /**
     * Sets the value of the rest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rest }
     *     
     */
    public void setRest(Rest value) {
        this.rest = value;
    }

	public fr.inria.edelweiss.rif.ast.Term XML2AST() {
		// TODO Auto-generated method stub
		return null;
	}

}
