//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 10:15:40 AM CEST 
//


package fr.inria.edelweiss.rif.xml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2007/rif#}IRIMETA" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2007/rif#}sub"/>
 *         &lt;element ref="{http://www.w3.org/2007/rif#}super"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "meta",
    "sub",
    "_super"
})
@XmlRootElement(name = "Subclass")
public class Subclass {

    protected Id id;
    protected Meta meta;
    @XmlElement(required = true)
    protected Sub sub;
    @XmlElement(name = "super", required = true)
    protected Super _super;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the sub property.
     * 
     * @return
     *     possible object is
     *     {@link Sub }
     *     
     */
    public Sub getSub() {
        return sub;
    }

    /**
     * Sets the value of the sub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sub }
     *     
     */
    public void setSub(Sub value) {
        this.sub = value;
    }

    /**
     * Gets the value of the super property.
     * 
     * @return
     *     possible object is
     *     {@link Super }
     *     
     */
    public Super getSuper() {
        return _super;
    }

    /**
     * Sets the value of the super property.
     * 
     * @param value
     *     allowed object is
     *     {@link Super }
     *     
     */
    public void setSuper(Super value) {
        this._super = value;
    }
    
    public fr.inria.edelweiss.rif.ast.Subclass XML2AST() {
    	return fr.inria.edelweiss.rif.ast.Subclass.create(this.sub.XML2AST(), this._super.XML2AST()) ;
    }

}
