prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:disjoint (?shape, ?sh, ?vis, ?s, ?p, ?q, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  ?s ?p ?o 
  bind (not exists { ?s ?q ?o } as ?suc)
    
  bind (st:report(sh:disjoint, ?sh, ?shape, ?s,  ?p, ?o, ?suc, ?vis) as ?b)
  
}
