prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:minCount (?shape, ?sh, ?vis, ?s, ?p, ?m, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  bind (sh:count(?s, ?p) as ?val)
  bind (?val >= ?m as ?suc)
  bind (st:report(sh:minCount, ?sh, ?shape, ?s, ?p, ?val, ?suc, ?vis) as ?b)
}

