prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {  
    ?sh sh:minCount|sh:maxCount ?m ; ?q ?m                       
  }

  bind (sh:mcount(?q, sh:count(?s, ?p), ?m)    as ?suc)  
  bind (st:report(?q, ?sh, ?shape, ?s, ?suc, ?vis) as ?b)
}

