prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s, ?p){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  graph ?shape {  
    ?sh sh:not ?cst  
  }
    
  bind (! sh:hasProperty(?shape, ?cst, false, ?s, ?p) as ?suc)
  
  bind (st:report(sh:shape, ?sh, ?shape, ?s, ?suc, ?vis) as ?b)
}
