prefix sh: <http://www.w3.org/ns/shacl#> 

template sh:hasValue (?shape, ?sh, ?vis, ?s, ?p, ?v, ?o){
  sh:safe(?shape, ?sh, ?suc)
}
where {

  bind (
    exists { ?s ?p ?o filter coalesce(?o = ?v, false) }
  as ?suc)
  
  bind (st:report(sh:hasValue, ?sh, ?shape,  ?s, ?p, ?v, ?suc, ?vis) as ?b)
}
