#
# SHACL Interpreter
# http://w3c.github.io/data-shapes/shacl/
# Functions are defined in resources/function/datashape, see target.rq and main.rq
#
# main: shapes with targets
# core: shape constraints (property, path, constraint, and, or, not, closed)
# path:       property path constraint
# constraint: node constraint
#
# Olivier Corby - Wimmics Inria I3S - 2016-2019
#
prefix sh: <http://www.w3.org/ns/shacl#> 

template st:start(?shapeGraph) {
    ?g
}
where {
  bind (coalesce(?shapeGraph, st:get(st:shape), st:shape) as ?shape)
  bind (coalesce(st:get(st:function), sh:shacl) as ?fun)
  bind (funcall(?fun, ?shape) as ?g)
}
