#
# defaut processing of a variable is st:apply-templates 
#
# Olivier Corby, Wimmics Inria I3S, 2014
#
template st:profile(?in) {

}
where {}

#
# extended datatype xt:graph is a string which represents a Turtle (sub)graph
# display it as is
#
function st:process(?in) { 
  if (isBlank(?in), st:blank(?in),	  
  if (isURI(?in), st:clean(st:turtle(?in)),
  if (datatype(?in) = xt:graph, st:clean(str(?in)),
  st:literal(st:clean(st:turtle(?in))))))
}


function st:clean(?in){
    replace(?in, "<", "&lt;") 		
}

function st:literal(?lit){
   st:format("<span class='literal'>%s</span>", replace(?lit, "\\\\n", "\n"))
}
  
function st:blank(?in){
  st:format(
    "<span id='%s'>%s</span>", 
    st:id(?in), st:apply-templates(?in))
}

function st:id(?in){
  coalesce(
    concat("it", st:vget(?in, st:id)), 
    concat("ab", st:index()))
}
      
function st:default(?in) {
   st:turtle(?in)
}



