#
# Turtle Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
template st:type {
"<span class='type'>"

  group {
  
     if (bound(?pr), "<span class='tag'>", "")        
         "a " 
     if (bound(?pr), "</span>", "")  
     
     if (?refer, st:turtle(?c), ?c)  
     
     if (bound(?pr), st:call-template(st:provenance, ?pr), "")
     
     ; separator = concat(" ;", st:nl()) 
  }
  
  "</span>"
  if (?rest, concat(" ;", st:nl()), "")
}
where {
  values ?p { rdf:type }
  ?in ?p ?c 
  bind (kg:provenance(?p) as ?pr)
  
    bind(
    exists { ?in ?q ?v . filter (?q != rdf:type) }
    as ?rest)
    
    bind(isBlank(?c) && exists { ?x ?q ?c . filter(?in != ?x) }
    as ?refer)
}
