template {
  ?suc  
}
where {
  ?in a owl:NamedIndividual, ?t
  
  filter (
    isURI(?in) ||
    not exists { ?x ?p ?in }
  )
 
 bind (isURI(?t) ||
   st:call-template-with(st:superexp, st:superClassExpression, ?t) 
 as ?suc)
 
 filter(st:visit(st:err("individual"), ?in, ?suc))

      
}


