template st:edges {
  "\"edges\":[\n"
  
  group { 
  
    format {
        '{"source": "%s", "target": "%s", "label": "%s", "id": "e%s", "class": "%s", "group": "%s" }'
        us:get(?s) us:get(?o) us:label(?p) kg:number() us:edgeClass(?g, ?p) us:edgeGroup(?g, ?p)
    }
    
    ; separator = ",\n"
  }
  
  "\n]\n"
} 
where {
    select * where {
        graph ?g { ?s ?p ?o }
        bind (us:triple(?s, ?p, ?o) as ?ss)
    } 
    order by ?p ?s ?o
    limit 5000
}
