template st:edges {
  "\"edges\":[\n"
  
  group { 
  
    format {
        '{"source": "%s", "target": "%s", "label": "%s", "id": "e%s" }'
        us:get(?s) us:get(?o) us:label(?p) kg:number()
    }
    
    ; separator = ",\n"
  }
  
  "\n]\n"
} 
where {
  select * where {
    ?s ?p ?o 
  }
  order by ?s ?o ?p
}
