template st:graph {
  str(?node)
  ","
  str(?edge)
} 
where {
    bind (xt:print('graph size', xt:size(xt:graph())) as ?tmp)
    
    bind (us:start() as ?start)
    
    bind (st:call-template(st:edges) as ?edge)
    
    bind (st:call-template(st:nodes) as ?node)
        
}
