template st:nodes {
  "\"nodes\":[\n"
  group {
    format {
        '{"id": "%s", "label": "%s", "group": "%s"}'
        
        us:get(?s) us:label(?s)
        if (isURI(?s), 1, if (isBlank(?s), 2, 3))
        }
    ; separator = ",\n"
  }
  "\n]\n"
} where {
  bind (us:start() as ?start)
  {select distinct ?s where {
    { ?s ?p ?o } union { ?o ?p ?s }
  } order by ?s}
  bind (us:record(?s) as ?tmp)
}
