template st:profile {}
where {}

function us:start() {
    set(?map = xt:map())
}

function us:record(?s) {
   xt:set(?map, ?s, coalesce(xt:get(?map, ?s), concat('n', kg:number())))
}

function us:get(?s) {
    xt:get(?map, ?s)
}

function us:declare(?fun) {
    set(?pretty = ?fun)
}

function us:label(?s) {
    if (bound(?pretty), us:pretty(funcall(?pretty, ?s)), us:pretty(?s))
}

function us:pretty(?s) {
    if (isBlank(?s), "",
    if (isLiteral(?s), us:literal(?s), us:uri(?s)))
}

function us:uri(?u) {
    if (contains(?u, ".jpg"), us:shorten(st:turtle(?u, true)), st:turtle(?u, true))
}

function us:shorten(?l) {
    let (?s = if (strlen(?l) > 50, concat(substr(?l, 1, 50), "..."), ?l)) { ?s }
}

function us:literal(?l) {
    let (?s = us:shorten(?l)) {
        replace(replace(str(?s), "\n", ""), "\"", "'")
    }
}
