
package wsimport.KgramWS;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RemoteProducer", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RemoteProducer {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "load", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.Load")
    @ResponseWrapper(localName = "loadResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.LoadResponse")
    public void load();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "reset", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.Reset")
    @ResponseWrapper(localName = "resetResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.ResetResponse")
    public void reset();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.QueryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "initEngineFromSQL", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.InitEngineFromSQL")
    @ResponseWrapper(localName = "initEngineFromSQLResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.InitEngineFromSQLResponse")
    public void initEngineFromSQL(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "runRule", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.RunRule")
    @ResponseWrapper(localName = "runRuleResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.RunRuleResponse")
    public void runRule();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadRDF", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.UploadRDF")
    @ResponseWrapper(localName = "uploadRDFResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.UploadRDFResponse")
    public void uploadRDF(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEndpoint", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.GetEndpoint")
    @ResponseWrapper(localName = "getEndpointResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.GetEndpointResponse")
    public String getEndpoint();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEdges", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.GetEdges")
    @ResponseWrapper(localName = "getEdgesResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.GetEdgesResponse")
    public String getEdges(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initEngine", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.InitEngine")
    @ResponseWrapper(localName = "initEngineResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.InitEngineResponse")
    public void initEngine();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setEndpoint", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.SetEndpoint")
    @ResponseWrapper(localName = "setEndpointResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.SetEndpointResponse")
    public void setEndpoint(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "loadRDF", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.LoadRDF")
    @ResponseWrapper(localName = "loadRDFResponse", targetNamespace = "http://webservice.kgramserver.edelweiss.inria.fr/", className = "wsimport.KgramWS.LoadRDFResponse")
    public void loadRDF(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
