prefix cal: <http://ns.inria.fr/sparql-extension/calendar/>
template st:agenda {

format {
  """
  <pre>
      \n%s\n
      Mo Tu We Th Fr Sa Su \n
      %s
  </pre>
  """
  
  cal:month(?m)
  group {
	  if (?n = 1, xt:space(cal:num(?jour) - 1), "")
	  if (?n < 10, " ", "") ?n " "
	  if (?jour = "Sunday", "\n", "")
	  ; separator = ""
  }
}    
    ; separator = "\n"                   
}
where {
    bind (unnest(xt:iota(12)) as ?m)
    bind (unnest(xt:iota(cal:days(?y, ?m))) as ?n)
    bind (xsd:date(concat(?y, "-", ?m, "-", ?n)) as ?day)
    bind (xt:day(?day) as ?jour)
    
    
}
group by ?m
order by ?m
values ?y { 2015 }

function xt:space(?n) {
      if (?n = 0, "", concat("   " , xt:space(?n - 1))) 
    }