prefix ft: <http://ns.inria.fr/sparql-template/format/calendar/>
template st:main(?year) {
  st:call-template(st:head, ?year)

  format {
    ft:main.html
    st:call-template(st:calendar, ?year)
  }

}
where {
  
}
