#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  st:prolog() 
  st:kw("construct") " "   st:call-template(sp:construct, ?in)
  st:nl()
  st:kw("where") " {" 
     box {
      st:call-template(sp:listnl, ?where)
     }
  "}"
  st:nl()
  ?group
  ?order
  if (bound(?l), concat(st:kw("limit"),  " ", ?l, st:nl()), "")  
  if (bound(?o), concat(st:kw("offset"), " ", ?o, st:nl()), "") 
  ?having 
  
   st:call-template(sp:values, ?in)

}
where {
?in a sp:Construct ;
    sp:where ?where

optional { ?in sp:groupBy  ?group }
optional { ?in sp:orderBy  ?order }
optional { ?in sp:having   ?having }
optional { ?in sp:limit  ?l }
optional { ?in sp:offset ?o }
}



