#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  st:namespace() 
  st:kw("describe") " " st:call-template(sp:list, ?list)   
}
where {
  ?in a sp:Describe ;
  sp:resultNodes ?list
  minus { ?in sp:where ?w }
}



