#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  st:kw( "desc") "(" st:call-template(sp:list, ?e) ")"
}
where {
  ?in a sp:Desc ;
  sp:expression ?e
}



