#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
  "(" ?f " " xt:pprotect(?lab) " " ?r ")"
}
where {
  ?in a ?ope  ;
      sp:arg1 ?f ;
      sp:arg2 ?r 
}
values (?ope ?lab) {
(sp:lt  "<")
(sp:gt  ">")
(sp:le  "<=")
(sp:ge  ">=")
(sp:eq  "=")
(sp:ne  "!=")

(sp:add     "+")
(sp:mul     "*")
(sp:divide  "/")
(sp:sub     "-")

(sp:and "&&")
(sp:or  "||")

}



