#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template sp:from {
   st:kw("from") " " ?f st:nl() ; separator = ""
}
where {
  ?in sp:from/rdf:rest*/rdf:first ?f
}



