#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template st:mode(?m) {

   st:call-template(st:main)

}
where {
  bind (st:set(st:mode, ?m) as ?mode)
}



