#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
   st:kw( "optional") " {" 
      box {   
	st:call-template(sp:listnl, ?b)
      }  
   "}"
}
where {
  ?in a sp:Optional ;
      sp:elements ?b
}



