#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:<http://spinrdf.org/sp#> .

template  {
  "{" ?q  "}" 
}
where {
  ?in a sp:SubQuery ;
    sp:query ?q 
  
}



