#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template {
    
      ?e1
      st:nl() st:kw( "union") st:nl() 
      ?e2
       
}
where {
  ?in a sp:Union ; 
      sp:elements ?l 
  ?l rdf:first ?e1 ;
      rdf:rest/rdf:first ?e2
}



