#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:<http://spinrdf.org/sp#> .

template  {
  st:kw( "values") " (" 
    st:call-template(sp:list, ?var)    
  ") {"
     box { ?list }
  "}"
}
where {
  ?in a sp:Values ;
    sp:variables ?var ;
    sp:values ?list
  
}



