template st:collection(?x, ?p, ?y) {
   "<" st:turtle(?p, true) " rdf:parseType='Collection'>" 
   
   box {
    st:call-template(st:list, ?y) 
   }
   
   "</" st:turtle(?p, true) ">"
}
where {
  
}
