template (?x, ?p, ?y) {
   '"' st:turtle(?p, true) '" : '
   '{ "@type" : "' st:turtle(datatype(?y), true) '", '
     '"@value" : "' str(?y) '"}'
   
}
where {
   ?x ?p ?y
   filter (isLiteral(?y) 
   && datatype(?y) != rdf:langString)
}
