#
# JSON LD Transformation
#
# Olivier Corby - Wimmics INRIA I3S - 2015
#

template st:start {

  st:call-template(st:head)
  
  str(?body)
  
  st:call-template(st:tail)
}
where {
   bind(st:call-template(st:main) as ?body )
}