prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s) {
  ?suc
}
where {

  graph ?shape {
    ?sh sh:targetClass ?c 
    optional { ?sh sh:filterShape ?fs }  
  }
  
  ?s a ?c

  filter ( ! bound(?fs) || sh:testShape(?shape, ?fs, ?s) )
  bind (sh:hasShape(?shape, ?sh, ?vis, ?s) as ?suc)
}
