#
# Inner shapes may have no scope
#
prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s) {
  ?suc
}
where {

  graph ?shape {
    ?x sh:shape|sh:filterShape|sh:and|sh:or|sh:not ?sh
    filter not exists { 
      ?sh sh:targetNode|sh:targetClass|sh:targetSubjectsOf|sh:targetObjectsOf ?scope }
    optional { ?sh sh:filterShape ?fs }  
  }
        
  filter ( ! bound(?fs) || sh:testShape(?shape, ?fs, ?s) )
  
  bind (sh:hasShape(?shape, ?sh, ?vis, ?s) as ?suc)
}
