#
# Data Shape Validator
# http://w3c.github.io/data-shapes/shacl/
#
# main: shapes with scopes
# core: shape constraints (property, inverseProperty, constraint, and, or, not, closed)
# property:   property constraint
# inverse:    inverse property constraint
# constraint: node constraint
#
# Olivier Corby - Inria I3S - 2016
#
prefix sh: <http://www.w3.org/ns/shacl#> 

template st:start {
  st:call-template(st:main, ?shape)
}
where {
  bind (st:visit(st:start, st:trace) as ?vis) 
  bind (coalesce(st:get(st:shape), st:shape) as ?shape)
}
