prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?s) {
  ?suc
}
where {

  graph ?shape {   
    ?sh sh:targetSubjectsOf ?p  
    optional { ?sh sh:filterShape ?fs }  
  }
  

  { select distinct ?s ?p where { ?s ?p ?o } }
  
  filter ( ! bound(?fs) || sh:testShape(?shape, ?fs, ?s) )
  
  bind (sh:hasShape(?shape, ?sh, ?vis, ?s) as ?suc)
}


