prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?ls) {
  sh:safe(?shape, ?sh, ?suc)
}
where {
  values (?shape ?sh) { (UNDEF UNDEF) }
  
  values (?q ?m) { unnest(sh:getConstraint(sh:cstgeneric, ?shape, ?sh)) }  
  
  values ?s { unnest(?ls) }
    
  bind (coalesce(if (?q = sh:functioncst,  funcall(?m, ?shape, ?sh, ?s), funcall(?q, ?shape, ?s, ?m)), false) as ?suc )
  
  bind (st:report(?q, ?sh, ?shape, ?s, st:null, ?s, ?suc, ?vis) as ?b)
}

