prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?ls) {
    funcall(?q, ?shape, ?sh, ?vis, ?s, ?m)
}
where {
  values (?shape ?sh) { (UNDEF UNDEF) }
  
  values (?q ?m) { unnest(sh:getConstraint(sh:cstgeneric3, ?shape, ?sh)) }
  
  values ?s { unnest(?ls) }
}


