#
# Extension functions defined in the query
#
select 
(let (?f = define(st:fib(?n) = if (?n <= 2, 1, st:fib(?n - 1) + st:fib(?n - 2))),
    st:fib(10)) as ?fib)
(let (?g = define(st:fac(?n) = if (?n = 0, 1, ?n * st:fac(?n - 1))), 
    st:fac(10)) as ?fac)
(let (?fun = define(st:date() = 
let(?d = now(), concat(day(?d), "/", month(?d), "/", year(?d)))), 
st:date()) 
as ?date)
where {}