prefix ex: <http://example.org/math/>
select (4 * ex:leibniz(?n) as ?pi)
where  {


function ex:leibniz(?n) {
    let (
        ?x = reduce(kg:plus, maplist(ex:inv, xt:iota(1, ?n, 4))),
        ?y = reduce(kg:plus, maplist(ex:inv, xt:iota(3, ?n, 4)))){
       ?x - ?y
    }
}

function ex:inv(?n) { 1 / ?n }


}
values ?n { 1000000 }