prefix cn: <http://cdn.fr/schema/>
prefix o:  <http://dbpedia.org/ontology/>

template cn:href(?r, ?u, ?t, ?i) {

  "<div class='margin'>"
  
  if (?img, 
    concat(st:call-template(cn:img, ?i), "<br/>"), 
    "")
    
   if (isURI(?r) && ?isp, 
	st:call-template(st:navlab, ?r, ?t),
	st:call-template(cn:hlink, ?u, ?t))

  "</div>"
}
where {

  bind ( exists { ?r a ?tt . filter (?tt in (foaf:Person, o:Place)) 
  } as ?isp )
  
  bind (bound(?i) && strstarts(?i, "http://") as ?img)
  
}
