prefix cn: <http://cdn.fr/schema/>
template cn:list {
  """
  <table class='margin'>
  <tr>
  <td><a href='""" 
  st:plink(<http://fr.dbpedia.org/resource/Nice>, st:dbpedia)
  "'>Carte</a></td><td>&nbsp;</td>"

  group {
    "<td><a href='" st:misc(?query) "'>" str(?title) "</a></td><td>&nbsp;</td>"
  }
  
  """</tr>
  </table>
  """
}
where {

}
values (?query ?title){
  ("/data/query/cdnplace.rq" 	"Lieu")
  ("/data/query/cdnperson.rq" 	"Personne")
  ("/data/query/cdnfr.rq" 	"France")
  ("/data/query/cdneds.rq" 	"Savoie")
  ("/data/query/cdnmisc.rq" 	"Autre")
}