#
# Generate Century Index
# Hypertext link may trigger Corese server 
# Answer using SPARQL Template Transformation
#
prefix cn: <http://cdn.fr/schema/>

template cn:elem(?title) {
  format {
      """
      <td>
      <a href='%s'><span %s>%s</span></a>
      </td>
      <td>&nbsp;&nbsp;</td>
      """
  
      st:plink(?century)
      ?class
      ?date
  } 
}
where {

  bind (coalesce(st:get(st:min), -1000) as ?fst)
  bind (coalesce(st:get(st:max),  3000) as ?rst)
    
  ?century cn:start ?min ; cn:finish ?max ; rdfs:label ?date
  
  filter (?min >= ?fst && ?max <= ?rst)
  
  bind (if (?date = ?title, " class='bold'", "") as ?class)
     
}
order by ?min
