prefix cn: <http://cdn.fr/schema/>
template cn:list {

format {

  """
  <table class='margin'>
  <tr>
  <td><a href='%s'>Carte</a></td><td>&nbsp;</td>
  %s  
  </tr>
  </table>
  """
  
  st:plink(<http://fr.dbpedia.org/resource/Nice>, st:dbpedia)
  
  group {
    format {
      "<td><a href='%s'>%s</a></td><td>&nbsp;</td>"
      
      st:misc(?query)
      str(?title)
    }
  }
  
}
  
}
where {

}
values (?query ?title){
  ("/data/query/cdnplace.rq" 	"Lieu")
  ("/data/query/cdnperson.rq" 	"Personne")
  ("/data/query/cdnfr.rq" 	"France")
  ("/data/query/cdneds.rq" 	"Savoie")
  ("/data/query/cdnmisc.rq" 	"Autre")
}