#
# Generate Century Index
# Hypertext link may trigger Corese server 
# Answer using SPARQL Template Transformation
#
prefix cn: <http://cdn.fr/schema/>

template cn:elem(?title) {

    "<td><a href='"  st:plink(?century) "'>" 
    
    "<span" ?class ">" ?date "</span>"
    
    "</a></td>"
    "<td>&nbsp;&nbsp;</td>"
 
}
where {

  bind (coalesce(st:get(st:min), -1000) as ?fst)
  bind (coalesce(st:get(st:max),  3000) as ?rst)
    
  ?century cn:start ?min ; cn:finish ?max ; rdfs:label ?date
  
  filter (?min >= ?fst && ?max <= ?rst)
  
  bind (if (?date = ?title, " class='bold'", "") as ?class)
     
}
order by ?min
