template st:query {
format {
  """
  <h3>Query</h3>
  <form method='post' action='%s'>
    <textarea cols='60' rows='10' name='query'>
    %s    
    </textarea>
    <br/>
    <input type='submit' value='Submit'/>
  </form>
  """
  
  st:get(st:service)
  st:get(st:query)
}
}
where {
}