#
# Get list st:period from profile.ttl st:param
#
prefix cn: <http://cdn.fr/schema/>
template cn:rowtitle(?c) {

   format { 
    "<th>%s</th>"
    
    if (?label = "Antiquité", 
    if (?max <= 500, str(?label), "&nbsp;"),
    str(?label))
   }
}  
where {

  ?c cn:start ?min ; cn:finish ?max
   
  bind (unnest(st:get(st:text)) as ?label)
  
}
    