template st:equivClassExpression(?x) {
  ?suc
}
where {
    bind (
      if (isURI(?x), ?x != owl:Thing, 
         st:apply-templates-all(?x))
    as ?suc)
    
  filter(st:visit(st:equiv, ?x, ?suc))
}
