#
# Check if there is an unauthorized OWL property for equivClassExpression ?in
# return false in this case, otherwise template fails (return nothing)
#
template {
  false
}
where {
    ?in ?p ?y
    
    bind (
      ?p in (
        owl:equivalentClass, owl:intersectionOf, 
	owl:onProperty, owl:hasValue, 
	rdf:type
	)
      as ?suc)
     
      filter (st:visit(st:err("failEquiv"), ?in, ?suc))
      filter (! ?suc)
}
limit 1
