#
# Display a day in the calendar of a month
# May be a link or a number
# Calling context may have set st:content and st:date 
# (cf st:content/st:query )
#
template st:date(?date) {

  coalesce(
    st:call-template-with(st:get(st:content), st:get(st:date), ?date), 
    day(?date))
  
}
where {
  
}
