template st:enum(?year, ?f, ?l) {
format {
  "<tr>%s</tr>\n"

  group {
    format {
      """
      <td>%s</td>
      <td>&nbsp;&nbsp;</td>
      """
      
      st:call-template(st:monthtab, ?year, ?month)
     }
  }
}
}
where {

    bind (unnest(xt:iota(?f, ?l)) as ?month)
}