prefix cal: <http://ns.inria.fr/sparql-extension/calendar/>
template st:monthtab(?y, ?m) {
  format {
      """
      <h3 class='center'>%s</h3>   
      <table class='month'>
	<tr>%s</tr>
	<tr>    
	%s   
	%s    
	</tr>    
	%s    
      </table>
      """
      
  cal:month(?m)
  st:call-template(st:title)
  xt:td(?first - 1)
  
  group {            
	  "<td class='day'>"          
	  st:call-template(st:date, ?date)        
	  "</td>"                       
	  if (?day = "Sunday", "</tr>\n<tr>", "")
		  
	  ; separator = ""
  }
  
  if (?first + ?days - 1 <= 35 , "<tr><td>&nbsp;</td></tr>", "")   
  }

}
where {
    bind (cal:days(?y, ?m)       as ?days)
    bind (cal:num(xt:day(cal:date(?y, ?m, 1))) as ?first)
    bind (unnest(xt:iota(?days)) as ?n)
    bind (cal:date(?y, ?m, ?n)   as ?date)
    bind (xt:day(?date)          as ?day)        
}
