/* Generated By:JavaCC: Do not edit this line. SparqlCoreseConstants.java */
package fr.inria.corese.sparql.triple.javacc1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SparqlCoreseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 6;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int Q_IRIref = 8;
  /** RegularExpression Id. */
  int QNAME_NS = 9;
  /** RegularExpression Id. */
  int QNAME = 10;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 11;
  /** RegularExpression Id. */
  int VAR1 = 12;
  /** RegularExpression Id. */
  int VAR2 = 13;
  /** RegularExpression Id. */
  int ABASE = 14;
  /** RegularExpression Id. */
  int APREFIX = 15;
  /** RegularExpression Id. */
  int ATLIST = 16;
  /** RegularExpression Id. */
  int ATPATH = 17;
  /** RegularExpression Id. */
  int LANGTAG = 18;
  /** RegularExpression Id. */
  int A2Z = 19;
  /** RegularExpression Id. */
  int A2ZN = 20;
  /** RegularExpression Id. */
  int KW_A = 21;
  /** RegularExpression Id. */
  int BASE = 22;
  /** RegularExpression Id. */
  int PREFIX = 23;
  /** RegularExpression Id. */
  int SELECT = 24;
  /** RegularExpression Id. */
  int DESCRIBE = 25;
  /** RegularExpression Id. */
  int CONSTRUCT = 26;
  /** RegularExpression Id. */
  int RULE = 27;
  /** RegularExpression Id. */
  int ASK = 28;
  /** RegularExpression Id. */
  int TEMPLATE = 29;
  /** RegularExpression Id. */
  int DISTINCT = 30;
  /** RegularExpression Id. */
  int SEPARATOR = 31;
  /** RegularExpression Id. */
  int REDUCED = 32;
  /** RegularExpression Id. */
  int LIMIT = 33;
  /** RegularExpression Id. */
  int OFFSET = 34;
  /** RegularExpression Id. */
  int ORDER = 35;
  /** RegularExpression Id. */
  int BY = 36;
  /** RegularExpression Id. */
  int RELAX = 37;
  /** RegularExpression Id. */
  int ASC = 38;
  /** RegularExpression Id. */
  int DESC = 39;
  /** RegularExpression Id. */
  int NAMED = 40;
  /** RegularExpression Id. */
  int FROM = 41;
  /** RegularExpression Id. */
  int WHERE = 42;
  /** RegularExpression Id. */
  int GRAPH = 43;
  /** RegularExpression Id. */
  int SERVICE = 44;
  /** RegularExpression Id. */
  int OPTIONAL = 45;
  /** RegularExpression Id. */
  int UNION = 46;
  /** RegularExpression Id. */
  int MINUSP = 47;
  /** RegularExpression Id. */
  int NOT = 48;
  /** RegularExpression Id. */
  int SCOPE = 49;
  /** RegularExpression Id. */
  int TRY = 50;
  /** RegularExpression Id. */
  int CATCH = 51;
  /** RegularExpression Id. */
  int THROW = 52;
  /** RegularExpression Id. */
  int STOP = 53;
  /** RegularExpression Id. */
  int LET = 54;
  /** RegularExpression Id. */
  int LETDYN = 55;
  /** RegularExpression Id. */
  int SET = 56;
  /** RegularExpression Id. */
  int STATIC = 57;
  /** RegularExpression Id. */
  int FOR = 58;
  /** RegularExpression Id. */
  int LOOP = 59;
  /** RegularExpression Id. */
  int IF = 60;
  /** RegularExpression Id. */
  int THEN = 61;
  /** RegularExpression Id. */
  int ELSE = 62;
  /** RegularExpression Id. */
  int EXIST = 63;
  /** RegularExpression Id. */
  int FILTER = 64;
  /** RegularExpression Id. */
  int LOAD = 65;
  /** RegularExpression Id. */
  int CLEAR = 66;
  /** RegularExpression Id. */
  int DROP = 67;
  /** RegularExpression Id. */
  int CREATE = 68;
  /** RegularExpression Id. */
  int ADD = 69;
  /** RegularExpression Id. */
  int TO = 70;
  /** RegularExpression Id. */
  int MOVE = 71;
  /** RegularExpression Id. */
  int COPY = 72;
  /** RegularExpression Id. */
  int INSERT = 73;
  /** RegularExpression Id. */
  int DELETE = 74;
  /** RegularExpression Id. */
  int WITH = 75;
  /** RegularExpression Id. */
  int USING = 76;
  /** RegularExpression Id. */
  int DEFAUT = 77;
  /** RegularExpression Id. */
  int ALL = 78;
  /** RegularExpression Id. */
  int INTO = 79;
  /** RegularExpression Id. */
  int SILENT = 80;
  /** RegularExpression Id. */
  int DATA = 81;
  /** RegularExpression Id. */
  int ERROR = 82;
  /** RegularExpression Id. */
  int RETURN = 83;
  /** RegularExpression Id. */
  int AGGREGATE = 84;
  /** RegularExpression Id. */
  int UNNEST = 85;
  /** RegularExpression Id. */
  int MAP = 86;
  /** RegularExpression Id. */
  int MAPLIST = 87;
  /** RegularExpression Id. */
  int MAPFIND = 88;
  /** RegularExpression Id. */
  int MAPFINDLIST = 89;
  /** RegularExpression Id. */
  int MAPMERGE = 90;
  /** RegularExpression Id. */
  int MAPEVERY = 91;
  /** RegularExpression Id. */
  int MAPANY = 92;
  /** RegularExpression Id. */
  int FUNCALL = 93;
  /** RegularExpression Id. */
  int EVAL = 94;
  /** RegularExpression Id. */
  int METHOD = 95;
  /** RegularExpression Id. */
  int APPLY = 96;
  /** RegularExpression Id. */
  int REDUCE = 97;
  /** RegularExpression Id. */
  int SELF = 98;
  /** RegularExpression Id. */
  int BOUND = 99;
  /** RegularExpression Id. */
  int COALESCE = 100;
  /** RegularExpression Id. */
  int SAMETERM = 101;
  /** RegularExpression Id. */
  int STR = 102;
  /** RegularExpression Id. */
  int STRDT = 103;
  /** RegularExpression Id. */
  int STRLANG = 104;
  /** RegularExpression Id. */
  int BNODE = 105;
  /** RegularExpression Id. */
  int URI = 106;
  /** RegularExpression Id. */
  int IRI = 107;
  /** RegularExpression Id. */
  int UUID = 108;
  /** RegularExpression Id. */
  int STRUUID = 109;
  /** RegularExpression Id. */
  int DTYPE = 110;
  /** RegularExpression Id. */
  int LANG = 111;
  /** RegularExpression Id. */
  int LANGMATCHES = 112;
  /** RegularExpression Id. */
  int CONTAINS = 113;
  /** RegularExpression Id. */
  int STRSTARTS = 114;
  /** RegularExpression Id. */
  int STRENDS = 115;
  /** RegularExpression Id. */
  int STRLEN = 116;
  /** RegularExpression Id. */
  int SUBSTR = 117;
  /** RegularExpression Id. */
  int UCASE = 118;
  /** RegularExpression Id. */
  int LCASE = 119;
  /** RegularExpression Id. */
  int STRBEFORE = 120;
  /** RegularExpression Id. */
  int STRAFTER = 121;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 122;
  /** RegularExpression Id. */
  int CONCAT = 123;
  /** RegularExpression Id. */
  int REPLACE = 124;
  /** RegularExpression Id. */
  int IS_URI = 125;
  /** RegularExpression Id. */
  int IS_IRI = 126;
  /** RegularExpression Id. */
  int IS_BLANK = 127;
  /** RegularExpression Id. */
  int IS_LITERAL = 128;
  /** RegularExpression Id. */
  int IS_NUMERIC = 129;
  /** RegularExpression Id. */
  int IS_EXTENSION = 130;
  /** RegularExpression Id. */
  int IS_SAFE = 131;
  /** RegularExpression Id. */
  int IS_UNDEFINED = 132;
  /** RegularExpression Id. */
  int IS_WELLFORMED = 133;
  /** RegularExpression Id. */
  int REGEX = 134;
  /** RegularExpression Id. */
  int RAND = 135;
  /** RegularExpression Id. */
  int ROUND = 136;
  /** RegularExpression Id. */
  int FLOOR = 137;
  /** RegularExpression Id. */
  int CEIL = 138;
  /** RegularExpression Id. */
  int POWER = 139;
  /** RegularExpression Id. */
  int ABS = 140;
  /** RegularExpression Id. */
  int NOW = 141;
  /** RegularExpression Id. */
  int YEAR = 142;
  /** RegularExpression Id. */
  int MONTH = 143;
  /** RegularExpression Id. */
  int DAY = 144;
  /** RegularExpression Id. */
  int HOURS = 145;
  /** RegularExpression Id. */
  int MINUTES = 146;
  /** RegularExpression Id. */
  int SECONDS = 147;
  /** RegularExpression Id. */
  int TIMEZONE = 148;
  /** RegularExpression Id. */
  int TZ = 149;
  /** RegularExpression Id. */
  int MD5 = 150;
  /** RegularExpression Id. */
  int SHA1 = 151;
  /** RegularExpression Id. */
  int SHA256 = 152;
  /** RegularExpression Id. */
  int SHA384 = 153;
  /** RegularExpression Id. */
  int SHA512 = 154;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 155;
  /** RegularExpression Id. */
  int SUM = 156;
  /** RegularExpression Id. */
  int SAMPLE = 157;
  /** RegularExpression Id. */
  int AVG = 158;
  /** RegularExpression Id. */
  int MIN = 159;
  /** RegularExpression Id. */
  int MAX = 160;
  /** RegularExpression Id. */
  int TRUE = 161;
  /** RegularExpression Id. */
  int FALSE = 162;
  /** RegularExpression Id. */
  int S_MORE = 163;
  /** RegularExpression Id. */
  int PRAGMA = 164;
  /** RegularExpression Id. */
  int GROUP = 165;
  /** RegularExpression Id. */
  int FORMAT = 166;
  /** RegularExpression Id. */
  int BOX = 167;
  /** RegularExpression Id. */
  int IBOX = 168;
  /** RegularExpression Id. */
  int SBOX = 169;
  /** RegularExpression Id. */
  int HAVING = 170;
  /** RegularExpression Id. */
  int VALUES = 171;
  /** RegularExpression Id. */
  int BIND = 172;
  /** RegularExpression Id. */
  int UNDEF = 173;
  /** RegularExpression Id. */
  int COUNT = 174;
  /** RegularExpression Id. */
  int SCORE = 175;
  /** RegularExpression Id. */
  int AS = 176;
  /** RegularExpression Id. */
  int SORTED = 177;
  /** RegularExpression Id. */
  int ALL2 = 178;
  /** RegularExpression Id. */
  int CURRENT = 179;
  /** RegularExpression Id. */
  int DIRECT2 = 180;
  /** RegularExpression Id. */
  int COLON2 = 181;
  /** RegularExpression Id. */
  int TUPLE = 182;
  /** RegularExpression Id. */
  int TRIPLE = 183;
  /** RegularExpression Id. */
  int SUBJECT = 184;
  /** RegularExpression Id. */
  int PREDICATE = 185;
  /** RegularExpression Id. */
  int OBJECT = 186;
  /** RegularExpression Id. */
  int IS_TRIPLE = 187;
  /** RegularExpression Id. */
  int SPARQL_COMPARE = 188;
  /** RegularExpression Id. */
  int XPATH = 189;
  /** RegularExpression Id. */
  int FUNCTION = 190;
  /** RegularExpression Id. */
  int LAMBDA = 191;
  /** RegularExpression Id. */
  int QUERY = 192;
  /** RegularExpression Id. */
  int PACKAGE = 193;
  /** RegularExpression Id. */
  int IN = 194;
  /** RegularExpression Id. */
  int EQ2 = 195;
  /** RegularExpression Id. */
  int NE2 = 196;
  /** RegularExpression Id. */
  int BEGIN_WITH = 197;
  /** RegularExpression Id. */
  int SPEC = 198;
  /** RegularExpression Id. */
  int SAME = 199;
  /** RegularExpression Id. */
  int GENERALISATION = 200;
  /** RegularExpression Id. */
  int STRICT_GENERALISATION = 201;
  /** RegularExpression Id. */
  int EQ_LANG = 202;
  /** RegularExpression Id. */
  int INTEGER = 203;
  /** RegularExpression Id. */
  int DECIMAL = 204;
  /** RegularExpression Id. */
  int DOUBLE = 205;
  /** RegularExpression Id. */
  int EXPONENT = 206;
  /** RegularExpression Id. */
  int QUOTE_3D = 207;
  /** RegularExpression Id. */
  int QUOTE_3S = 208;
  /** RegularExpression Id. */
  int ECHAR = 209;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 210;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 211;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 212;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 213;
  /** RegularExpression Id. */
  int DIGITS = 214;
  /** RegularExpression Id. */
  int HEX = 215;
  /** RegularExpression Id. */
  int LPAREN = 216;
  /** RegularExpression Id. */
  int RPAREN = 217;
  /** RegularExpression Id. */
  int LBRACE = 218;
  /** RegularExpression Id. */
  int RBRACE = 219;
  /** RegularExpression Id. */
  int LBRACKET = 220;
  /** RegularExpression Id. */
  int RBRACKET = 221;
  /** RegularExpression Id. */
  int ANON = 222;
  /** RegularExpression Id. */
  int SEMICOLON = 223;
  /** RegularExpression Id. */
  int COMMA = 224;
  /** RegularExpression Id. */
  int DOT = 225;
  /** RegularExpression Id. */
  int EQ = 226;
  /** RegularExpression Id. */
  int NE = 227;
  /** RegularExpression Id. */
  int LTLT = 228;
  /** RegularExpression Id. */
  int GTGT = 229;
  /** RegularExpression Id. */
  int LT = 230;
  /** RegularExpression Id. */
  int GT = 231;
  /** RegularExpression Id. */
  int LE = 232;
  /** RegularExpression Id. */
  int GE = 233;
  /** RegularExpression Id. */
  int BANG = 234;
  /** RegularExpression Id. */
  int TILDE = 235;
  /** RegularExpression Id. */
  int COLON = 236;
  /** RegularExpression Id. */
  int SC_OR = 237;
  /** RegularExpression Id. */
  int SC_AND = 238;
  /** RegularExpression Id. */
  int PLUS = 239;
  /** RegularExpression Id. */
  int MINUS = 240;
  /** RegularExpression Id. */
  int STAR = 241;
  /** RegularExpression Id. */
  int SLASH = 242;
  /** RegularExpression Id. */
  int QM = 243;
  /** RegularExpression Id. */
  int BAR = 244;
  /** RegularExpression Id. */
  int DATATYPE = 245;
  /** RegularExpression Id. */
  int AT = 246;
  /** RegularExpression Id. */
  int VAR3 = 247;
  /** RegularExpression Id. */
  int NCCHAR1p = 248;
  /** RegularExpression Id. */
  int NCCHAR1 = 249;
  /** RegularExpression Id. */
  int NCCHAR = 250;
  /** RegularExpression Id. */
  int NCNAME_PREFIX = 251;
  /** RegularExpression Id. */
  int NCNAME = 252;
  /** RegularExpression Id. */
  int BLANKNAME = 253;
  /** RegularExpression Id. */
  int VARNAME = 254;
  /** RegularExpression Id. */
  int LOCAL_ESC = 255;
  /** RegularExpression Id. */
  int PERCENT = 256;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<Q_IRIref>",
    "<QNAME_NS>",
    "<QNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "\"@base\"",
    "\"@prefix\"",
    "\"@list\"",
    "\"@path\"",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"describe\"",
    "\"construct\"",
    "\"rule\"",
    "\"ask\"",
    "\"template\"",
    "\"distinct\"",
    "\"separator\"",
    "\"reduced\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"relax\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"graph\"",
    "\"service\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"not\"",
    "\"scope\"",
    "\"try\"",
    "\"catch\"",
    "\"throw\"",
    "\"stop\"",
    "\"let\"",
    "\"letdyn\"",
    "\"set\"",
    "\"static\"",
    "\"for\"",
    "\"loop\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"exists\"",
    "\"filter\"",
    "\"load\"",
    "\"clear\"",
    "\"drop\"",
    "\"create\"",
    "\"add\"",
    "\"to\"",
    "\"move\"",
    "\"copy\"",
    "\"insert\"",
    "\"delete\"",
    "\"with\"",
    "\"using\"",
    "\"default\"",
    "\"all\"",
    "\"into\"",
    "\"silent\"",
    "\"data\"",
    "\"error\"",
    "\"return\"",
    "\"aggregate\"",
    "\"unnest\"",
    "\"map\"",
    "\"maplist\"",
    "\"mapfind\"",
    "\"mapfindlist\"",
    "\"mapmerge\"",
    "\"mapevery\"",
    "\"mapany\"",
    "\"funcall\"",
    "\"eval\"",
    "\"method\"",
    "\"apply\"",
    "\"reduce\"",
    "\"self\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"sameTerm\"",
    "\"str\"",
    "\"strdt\"",
    "\"strlang\"",
    "\"bnode\"",
    "\"uri\"",
    "\"iri\"",
    "\"uuid\"",
    "\"struuid\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"contains\"",
    "\"strstarts\"",
    "\"strends\"",
    "\"strlen\"",
    "\"substr\"",
    "\"ucase\"",
    "\"lcase\"",
    "\"strbefore\"",
    "\"strafter\"",
    "\"encode_for_uri\"",
    "\"concat\"",
    "\"replace\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"isExtension\"",
    "\"safe\"",
    "\"isUndefined\"",
    "\"isWellFormed\"",
    "\"regex\"",
    "\"rand\"",
    "\"round\"",
    "\"floor\"",
    "\"ceil\"",
    "\"power\"",
    "\"abs\"",
    "\"now\"",
    "\"year\"",
    "\"month\"",
    "\"day\"",
    "\"hours\"",
    "\"minutes\"",
    "\"seconds\"",
    "\"timezone\"",
    "\"tz\"",
    "\"md5\"",
    "\"sha1\"",
    "\"sha256\"",
    "\"sha384\"",
    "\"sha512\"",
    "\"group_concat\"",
    "\"sum\"",
    "\"sample\"",
    "\"avg\"",
    "\"min\"",
    "\"max\"",
    "\"true\"",
    "\"false\"",
    "\"more\"",
    "\"pragma\"",
    "\"group\"",
    "\"format\"",
    "\"box\"",
    "\"ibox\"",
    "\"sbox\"",
    "\"having\"",
    "\"values\"",
    "\"bind\"",
    "\"undef\"",
    "\"count\"",
    "\"score\"",
    "\"as\"",
    "\"sorted\"",
    "\"all::\"",
    "\"current::\"",
    "\"direct::\"",
    "\"::\"",
    "\"tuple\"",
    "\"triple\"",
    "\"subject\"",
    "\"predicate\"",
    "\"object\"",
    "\"isTriple\"",
    "\"sparql-compare\"",
    "\"xpath\"",
    "\"function\"",
    "\"lambda\"",
    "\"query\"",
    "\"package\"",
    "\"in\"",
    "\"==\"",
    "\"!==\"",
    "\"^\"",
    "\"<=:\"",
    "\"=:\"",
    "\">=:\"",
    "\">:\"",
    "\"~=\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<HEX>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"?\"",
    "\"|\"",
    "\"^^\"",
    "\"@\"",
    "<VAR3>",
    "<NCCHAR1p>",
    "<NCCHAR1>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<BLANKNAME>",
    "<VARNAME>",
    "<LOCAL_ESC>",
    "<PERCENT>",
  };

}
