/* Generated By:JavaCC: Do not edit this line. SparqlCoreseConstants.java */
package fr.inria.corese.sparql.triple.javacc1;

public interface SparqlCoreseConstants {

  int EOF = 0;
  int WS = 6;
  int SINGLE_LINE_COMMENT = 7;
  int Q_IRIref = 8;
  int QNAME_NS = 9;
  int QNAME = 10;
  int BLANK_NODE_LABEL = 11;
  int VAR1 = 12;
  int VAR2 = 13;
  int ABASE = 14;
  int APREFIX = 15;
  int ATLIST = 16;
  int ATPATH = 17;
  int LANGTAG = 18;
  int A2Z = 19;
  int A2ZN = 20;
  int KW_A = 21;
  int BASE = 22;
  int PREFIX = 23;
  int SELECT = 24;
  int DESCRIBE = 25;
  int CONSTRUCT = 26;
  int RULE = 27;
  int ASK = 28;
  int TEMPLATE = 29;
  int DISTINCT = 30;
  int SEPARATOR = 31;
  int REDUCED = 32;
  int LIMIT = 33;
  int OFFSET = 34;
  int ORDER = 35;
  int BY = 36;
  int RELAX = 37;
  int ASC = 38;
  int DESC = 39;
  int NAMED = 40;
  int FROM = 41;
  int WHERE = 42;
  int GRAPH = 43;
  int SERVICE = 44;
  int OPTIONAL = 45;
  int UNION = 46;
  int MINUSP = 47;
  int NOT = 48;
  int SCOPE = 49;
  int LET = 50;
  int LETDYN = 51;
  int SET = 52;
  int FOR = 53;
  int LOOP = 54;
  int IF = 55;
  int THEN = 56;
  int ELSE = 57;
  int EXIST = 58;
  int FILTER = 59;
  int LOAD = 60;
  int CLEAR = 61;
  int DROP = 62;
  int CREATE = 63;
  int ADD = 64;
  int TO = 65;
  int MOVE = 66;
  int COPY = 67;
  int INSERT = 68;
  int DELETE = 69;
  int WITH = 70;
  int USING = 71;
  int DEFAUT = 72;
  int ALL = 73;
  int INTO = 74;
  int SILENT = 75;
  int DATA = 76;
  int ERROR = 77;
  int RETURN = 78;
  int AGGREGATE = 79;
  int UNNEST = 80;
  int MAP = 81;
  int MAPLIST = 82;
  int MAPFIND = 83;
  int MAPFINDLIST = 84;
  int MAPMERGE = 85;
  int MAPEVERY = 86;
  int MAPANY = 87;
  int FUNCALL = 88;
  int EVAL = 89;
  int METHOD = 90;
  int APPLY = 91;
  int REDUCE = 92;
  int SELF = 93;
  int BOUND = 94;
  int COALESCE = 95;
  int SAMETERM = 96;
  int STR = 97;
  int STRDT = 98;
  int STRLANG = 99;
  int BNODE = 100;
  int URI = 101;
  int IRI = 102;
  int UUID = 103;
  int STRUUID = 104;
  int DTYPE = 105;
  int LANG = 106;
  int LANGMATCHES = 107;
  int CONTAINS = 108;
  int STRSTARTS = 109;
  int STRENDS = 110;
  int STRLEN = 111;
  int SUBSTR = 112;
  int UCASE = 113;
  int LCASE = 114;
  int STRBEFORE = 115;
  int STRAFTER = 116;
  int ENCODE_FOR_URI = 117;
  int CONCAT = 118;
  int REPLACE = 119;
  int IS_URI = 120;
  int IS_IRI = 121;
  int IS_BLANK = 122;
  int IS_LITERAL = 123;
  int IS_NUMERIC = 124;
  int IS_EXTENSION = 125;
  int IS_SAFE = 126;
  int IS_UNDEFINED = 127;
  int IS_WELLFORMED = 128;
  int REGEX = 129;
  int RAND = 130;
  int ROUND = 131;
  int FLOOR = 132;
  int CEIL = 133;
  int POWER = 134;
  int ABS = 135;
  int NOW = 136;
  int YEAR = 137;
  int MONTH = 138;
  int DAY = 139;
  int HOURS = 140;
  int MINUTES = 141;
  int SECONDS = 142;
  int TIMEZONE = 143;
  int TZ = 144;
  int MD5 = 145;
  int SHA1 = 146;
  int SHA256 = 147;
  int SHA384 = 148;
  int SHA512 = 149;
  int GROUP_CONCAT = 150;
  int SUM = 151;
  int SAMPLE = 152;
  int AVG = 153;
  int MIN = 154;
  int MAX = 155;
  int TRUE = 156;
  int FALSE = 157;
  int S_MORE = 158;
  int PRAGMA = 159;
  int GROUP = 160;
  int FORMAT = 161;
  int BOX = 162;
  int IBOX = 163;
  int SBOX = 164;
  int HAVING = 165;
  int VALUES = 166;
  int BIND = 167;
  int UNDEF = 168;
  int COUNT = 169;
  int SCORE = 170;
  int AS = 171;
  int SORTED = 172;
  int ALL2 = 173;
  int CURRENT = 174;
  int DIRECT2 = 175;
  int COLON2 = 176;
  int DEBUG = 177;
  int CHECK = 178;
  int NOSORT = 179;
  int TUPLE = 180;
  int TRIPLE = 181;
  int XPATH = 182;
  int FUNCTION = 183;
  int LAMBDA = 184;
  int QUERY = 185;
  int PACKAGE = 186;
  int IN = 187;
  int EQ2 = 188;
  int NE2 = 189;
  int BEGIN_WITH = 190;
  int STRICT_SPEC = 191;
  int SPEC = 192;
  int SAME = 193;
  int GENERALISATION = 194;
  int STRICT_GENERALISATION = 195;
  int EQ_LANG = 196;
  int INTEGER = 197;
  int DECIMAL = 198;
  int DOUBLE = 199;
  int EXPONENT = 200;
  int QUOTE_3D = 201;
  int QUOTE_3S = 202;
  int ECHAR = 203;
  int STRING_LITERAL1 = 204;
  int STRING_LITERAL2 = 205;
  int STRING_LITERAL_LONG1 = 206;
  int STRING_LITERAL_LONG2 = 207;
  int DIGITS = 208;
  int HEX = 209;
  int LPAREN = 210;
  int RPAREN = 211;
  int LBRACE = 212;
  int RBRACE = 213;
  int LBRACKET = 214;
  int RBRACKET = 215;
  int ANON = 216;
  int SEMICOLON = 217;
  int COMMA = 218;
  int DOT = 219;
  int EQ = 220;
  int NE = 221;
  int GT = 222;
  int LT = 223;
  int LE = 224;
  int GE = 225;
  int BANG = 226;
  int TILDE = 227;
  int COLON = 228;
  int SC_OR = 229;
  int SC_AND = 230;
  int PLUS = 231;
  int MINUS = 232;
  int STAR = 233;
  int SLASH = 234;
  int QM = 235;
  int BAR = 236;
  int DATATYPE = 237;
  int AT = 238;
  int VAR3 = 239;
  int NCCHAR1p = 240;
  int NCCHAR1 = 241;
  int NCCHAR = 242;
  int NCNAME_PREFIX = 243;
  int NCNAME = 244;
  int BLANKNAME = 245;
  int VARNAME = 246;
  int LOCAL_ESC = 247;
  int PERCENT = 248;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<Q_IRIref>",
    "<QNAME_NS>",
    "<QNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "\"@base\"",
    "\"@prefix\"",
    "\"@list\"",
    "\"@path\"",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"describe\"",
    "\"construct\"",
    "\"rule\"",
    "\"ask\"",
    "\"template\"",
    "\"distinct\"",
    "\"separator\"",
    "\"reduced\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"relax\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"graph\"",
    "\"service\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"not\"",
    "\"scope\"",
    "\"let\"",
    "\"letdyn\"",
    "\"set\"",
    "\"for\"",
    "\"loop\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"exists\"",
    "\"filter\"",
    "\"load\"",
    "\"clear\"",
    "\"drop\"",
    "\"create\"",
    "\"add\"",
    "\"to\"",
    "\"move\"",
    "\"copy\"",
    "\"insert\"",
    "\"delete\"",
    "\"with\"",
    "\"using\"",
    "\"default\"",
    "\"all\"",
    "\"into\"",
    "\"silent\"",
    "\"data\"",
    "\"error\"",
    "\"return\"",
    "\"aggregate\"",
    "\"unnest\"",
    "\"map\"",
    "\"maplist\"",
    "\"mapfind\"",
    "\"mapfindlist\"",
    "\"mapmerge\"",
    "\"mapevery\"",
    "\"mapany\"",
    "\"funcall\"",
    "\"eval\"",
    "\"method\"",
    "\"apply\"",
    "\"reduce\"",
    "\"self\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"sameTerm\"",
    "\"str\"",
    "\"strdt\"",
    "\"strlang\"",
    "\"bnode\"",
    "\"uri\"",
    "\"iri\"",
    "\"uuid\"",
    "\"struuid\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"contains\"",
    "\"strstarts\"",
    "\"strends\"",
    "\"strlen\"",
    "\"substr\"",
    "\"ucase\"",
    "\"lcase\"",
    "\"strbefore\"",
    "\"strafter\"",
    "\"encode_for_uri\"",
    "\"concat\"",
    "\"replace\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"isExtension\"",
    "\"safe\"",
    "\"isUndefined\"",
    "\"isWellFormed\"",
    "\"regex\"",
    "\"rand\"",
    "\"round\"",
    "\"floor\"",
    "\"ceil\"",
    "\"power\"",
    "\"abs\"",
    "\"now\"",
    "\"year\"",
    "\"month\"",
    "\"day\"",
    "\"hours\"",
    "\"minutes\"",
    "\"seconds\"",
    "\"timezone\"",
    "\"tz\"",
    "\"md5\"",
    "\"sha1\"",
    "\"sha256\"",
    "\"sha384\"",
    "\"sha512\"",
    "\"group_concat\"",
    "\"sum\"",
    "\"sample\"",
    "\"avg\"",
    "\"min\"",
    "\"max\"",
    "\"true\"",
    "\"false\"",
    "\"more\"",
    "\"pragma\"",
    "\"group\"",
    "\"format\"",
    "\"box\"",
    "\"ibox\"",
    "\"sbox\"",
    "\"having\"",
    "\"values\"",
    "\"bind\"",
    "\"undef\"",
    "\"count\"",
    "\"score\"",
    "\"as\"",
    "\"sorted\"",
    "\"all::\"",
    "\"current::\"",
    "\"direct::\"",
    "\"::\"",
    "\"debug\"",
    "\"check\"",
    "\"nosort\"",
    "\"tuple\"",
    "\"triple\"",
    "\"xpath\"",
    "\"function\"",
    "\"lambda\"",
    "\"query\"",
    "\"package\"",
    "\"in\"",
    "\"==\"",
    "\"!==\"",
    "\"^\"",
    "\"<:\"",
    "\"<=:\"",
    "\"=:\"",
    "\">=:\"",
    "\">:\"",
    "\"~=\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<HEX>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"?\"",
    "\"|\"",
    "\"^^\"",
    "\"@\"",
    "<VAR3>",
    "<NCCHAR1p>",
    "<NCCHAR1>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<BLANKNAME>",
    "<VARNAME>",
    "<LOCAL_ESC>",
    "<PERCENT>",
  };

}
