#
# Olivier Corby - Wimmics Inria I3S - 2013
#
template {
   "ClassAssertion(" ?t " " ?in ")"
}
where {
  ?in a ?t
  filter (!(strstarts(?t, owl:) 
     || strstarts(?t, rdf:) 
     || strstarts(?t, rdfs:)) )
}
