template st:superClassExpression(?x) {
  ?suc
}
where {
    bind (
      if (isURI(?x), ?x != owl:Thing, 
         st:apply-templates-all(?x)) 
    as ?suc)
      
   #filter(st:visit(st:err("super"), ?x, ?suc))
   filter(st:alreadyVisited(?x, "super", ?suc))
}
