#
# SPARQL-based RDF AST Pretty-printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
prefix sp:      <http://spinrdf.org/sp#> .

template sp:usingNamed {
   "using named " ?f "\n" ; separator = ""
}
where {
  ?in sp:usingNamed/rdf:rest*/rdf:first ?f
}



