#
# Event driven functions to trace Rule Engine
#

@public @beforeEntailment 
function us:beforeEntailment (re, path) {
	xt:print("before entailment", path)
}

@public @afterEntailment 
function us:afterEntailment(re, path) {
	xt:print("after entailment", path)
}

#@public
@beforeRule
function us:beforeRule(re, q) {
    xt:print("@beforeRule");
    xt:print(java:getAST(q))
}

@public @afterRule
function us:afterRule(re, q, res) {
    if (xt:size(res) > 0) { # && java:hasMetadata(java:getAST(q), "@test")) {
        xt:print("@afterRule");
        xt:print(java:getAST(q));
        xt:print(xt:size(res), res);
        xt:print()
    }
}
