template st:queryspin(?q) {
  """
  <h3>SPIN Query</h3>
  <form method='post' id='sparql' action='/spin/tosparql'>
  
    <input type='hidden' name='transform' value='""" st:get(st:transform) """' />
    
    <textarea cols='60' rows='15' id='query2' name='query'>"""str(?q)
    
  """</textarea>
    <br/>"""
    
    # st:call-template-with(st:server, st:submit, "sparql", "submit", coalesce(st:get(st:protocol), st:std))
       
   "<input type='submit' value='submit'"  st:call-template-with(st:server, st:submit)  " />"
   
    
  """  
  </form>
  """
}
where {
}