template st:query(?q) {
  """
  <h3>SPARQL Query</h3>
  <form method='post' action='/spin/tospin'>
    <input type='hidden' name='transform' value='""" st:get(st:transform) """' />
    
    <textarea cols='60' rows='15' name='query'>"""str(?q)
    
  """</textarea>
    <br/>
    <input type='submit' value='Submit'/>
  </form>
  """
}
where {
}