prefix sh: <http://www.w3.org/ns/shacl#> 

template  (?shape, ?sh, ?vis, ?ls, ?p, ?o) {
  if (bound(?o), 
    funcall(?oper, ?shape, ?sh, ?vis, ?s, ?p, ?b, ?o),
    funcall(?oper, ?shape, ?sh, ?vis, ?s, ?p, ?b))
}
where {
  values (?o ?shape ?sh) { (UNDEF UNDEF UNDEF) }
  
  values (?oper ?b) { unnest(sh:getConstraint(sh:generic4, ?shape, ?sh)) }  
  
  values ?s { unnest(?ls) }
}
