prefix sh: <http://www.w3.org/ns/shacl#> 

template (?shape, ?sh, ?vis, ?ls, ?p, ?o) {
  if (bound(?o), 
    st:call-template(?oper, ?shape, ?sh, ?vis, ?s, ?p, ?b, ?o),
    st:call-template(?oper, ?shape, ?sh, ?vis, ?s, ?p, ?b))
}
where {
  graph ?shape {  
    values ?oper { 
      #sh:equals sh:disjoint sh:maxCount sh:minCount
      #sh:and sh:or sh:xone sh:not 
      
      sh:pattern sh:uniqueLang sh:hasValue sh:lessThanOrEquals sh:lessThan  
      sh:qualifiedValueShape sh:sparql
    }
    ?sh ?oper ?b  
    filter if (?oper = sh:uniqueLang, sameTerm(?b, true), true)
  }
  values ?s { unnest(?ls) }

}
