template st:button {

  """<button type='button' class='btn btn-default' onClick='next(+1)'>next</button>"""
  """<button type='button' class='btn btn-default' onClick='next(-1)'>prev</button>"""
}
where {}
