template  st:class  {

  xt:nl(st:apply-templates-with-all(st:owlclass, ?in), 2)
  ; separator = ""
}
where {

  select distinct ?in where {
    values ?p { rdf:type  owl:disjointWith owl:equivalentClass  rdfs:subClassOf owl:hasKey owl:disjointUnionOf}
     ?in ?p ?y 
    filter (
      (isURI(?in)   && not exists { ?in a owl:Ontology }) ||
      (isBlank(?in) && not exists { ?x ?q ?in } )
    )
  # OWL vocabulary must not be pretty printed
      filter (! xt:system(?in))
        
  }
  order by ?in
        
}

