prefix p:    <http://fr.dbpedia.org/property/>
prefix o:    <http://dbpedia.org/ontology/>
prefix ft:  <http://ns.inria.fr/sparql-template/format/navlab/>

template st:descresource(?r) {
format {
  ft:resource.html
  str(?p)
  st:call-template(st:triple, ?r, ?p, ?v)
  }
}
where { 
    ?r ?p ?v
}
