#
# Link to server
#
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix o:    <http://dbpedia.org/ontology/>
prefix w:    <http://fr.wikipedia.org/wiki/>
prefix r:    <http://fr.dbpedia.org/resource/>
prefix p:    <http://fr.dbpedia.org/property/>
prefix ft:  <http://ns.inria.fr/sparql-template/format/navlab/>


template  st:display(?r, ?l) {
  format {
    ft:link.html
    st:pplink(?r)
    str(coalesce(?l, ?pr))
  }
}

where {
   bind (
   if (strstarts(?r, r:), concat(w:, (substr(?r, strlen(r:) + 1))), ?r) 
   as ?pr)   
}
 
