prefix o:   <http://dbpedia.org/ontology/>
prefix w:   <http://fr.wikipedia.org/wiki/>
prefix r:   <http://fr.dbpedia.org/resource/>
prefix p:   <http://fr.dbpedia.org/property/>
prefix ft:  <http://ns.inria.fr/sparql-template/format/navlab/>

template st:frame(?label, ?icon, ?body) {
format {
  ft:frame.html

  str(?label)
  
  if (?icon = "", "", 
      st:call-template(st:icon, ?label, ?icon)  )
      
  str(?body)    
}  
}
where {


    
}
