#
# Geolocate resource on a map given lat et long (openstreetmap)
#
prefix ft:  <http://ns.inria.fr/sparql-template/format/navlab/>

template st:omap(?r, ?lat, ?lon, ?list) {
  
    st:call-template(st:maplist, ft:map.html, xt:cons(xt:list(?r, ?lat, ?lon), ?list), "")
}
where {

}
