prefix o:    <http://dbpedia.org/ontology/>
prefix w:    <http://fr.wikipedia.org/wiki/>
prefix r:    <http://fr.dbpedia.org/resource/>
prefix p:  <http://fr.dbpedia.org/property/>

template st:page {

  st:head()

  st:call-template(st:selecttry)

  st:call-template-with(st:d3, st:frame)
   
  st:tail()
  
}
where {
}