template st:property(?r, ?p) {

  if (isLiteral(?n), str(?n),
    st:call-template(st:display, ?n, coalesce(?ln, ?n)))
    
    ; separator = " - "
  
}
where { 

  ?r ?p ?n  
  optional { ?n rdfs:label ?ln }
  
}
