prefix o:    <http://dbpedia.org/ontology/>
prefix w:    <http://fr.wikipedia.org/wiki/>
prefix r:    <http://fr.dbpedia.org/resource/>
prefix p:    <http://fr.dbpedia.org/property/>

template st:title(?r, ?l, ?i) {
 
  "<div class='center'>" 
  
  "<h2>"  str(?l) "</h2>"
  
 """<p>"""
    coalesce(str(?b), "")
    if (bound(?b) && bound(?d), " -- " , "")
    coalesce(str(?d), "")
  """</p>
  """
  
  "</div>"

}
where {
}