#
# Turtle Pretty Printer
# Olivier Corby, Wimmics Inria I3S, 2013
#
template st:open {

st:call-template-with(st:server, st:head)

"<h3>Result</h3>"

"\n<pre>\n"

  replace(st:prolog("@prefix"), "<", "&lt;")
  
}
where {

}

