package fr.inria.corese.w3cJunitTestsGenerator;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import fr.inria.corese.w3cJunitTestsGenerator.w3cTests.IW3cTest;

/**
 * Generates a JUnit test file for the W3C test suite.
 */
public class JUnitTestFileGenerator {

    private static final Logger logger = LogManager.getLogger(JUnitTestFileGenerator.class);

    private final URI manifestUri;
    private final String testName;
    private final List<IW3cTest> tests;
    private final Path exportPath;

    public JUnitTestFileGenerator(String testName, URI manifestUri, Path exportPath, List<IW3cTest> tests) {
        this.testName = testName;
        this.manifestUri = manifestUri;
        this.exportPath = exportPath.resolve(testName);
        this.tests = tests;
    }

    /**
     * Generates a JUnit test file for the W3C test suite.
     */
    public void generate() {

        // Initialize directories
        Path testDirectory = this.createDirectory(this.exportPath);

        // Generate file test
        String fileName = testName + "Test.java";
        Path testFile = this.generateTestFile(testDirectory, fileName);

        // Write test file
        try {
            Files.write(testFile, this.generateTestFileContent(testFile.toString(), fileName).getBytes());
            logger.info("Wrote test file: " + testFile);
        } catch (IOException e) {
            logger.error("Failed to write test file: " + testFile, e);
        }

    }

    /**
     * Creates a directory at the specified path if it does not already exist.
     * 
     * @param directoryPath The path to the directory to create.
     * @param directoryType The type of directory to create.
     */
    private Path createDirectory(Path directoryPath) {
        if (!Files.exists(directoryPath)) {
            try {
                Files.createDirectories(directoryPath);
                logger.info("Created directory: " + directoryPath);
            } catch (IOException e) {
                logger.error("Failed to create directory: " + directoryPath, e);
            }
        }
        return directoryPath;
    }

    /**
     * Generates a test file at the specified path if it does not already exist.
     * 
     * @param testDirectory The directory where the test file should be generated.
     * @param fileName      The name of the test file.
     * @return The path to the test file.
     */
    private Path generateTestFile(Path testDirectory, String fileName) {
        Path filePath = testDirectory.resolve(fileName);

        if (Files.exists(filePath)) {
            return filePath;
        }

        try {
            Files.createFile(filePath);
            logger.info("Created test file: " + filePath);
        } catch (IOException e) {
            logger.error("Failed to create test file: " + filePath, e);
        }
        return filePath;
    }

    /**
     * Generates the content of the test file.
     * 
     * @param path     The path of the file.
     * @param fileName The name of the file.
     * @return The content of the test file.
     */
    private String generateTestFileContent(String path, String fileName) {
        StringBuilder content = new StringBuilder();

        // Package
        content.append(this.getPackage(path, fileName));
        content.append("\n");
        content.append("\n");

        // Imports
        Set<String> imports = new HashSet<>();
        for (IW3cTest test : tests) {
            imports.addAll(test.getImports());
        }
        imports.addAll(this.defineImports());
        imports.stream().sorted().forEach(imp -> content.append("import ").append(imp).append(";\n"));
        content.append("\n");

        // Class comment
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        ZonedDateTime nowWithZone = ZonedDateTime.now();

        content.append("/**\n");
        content.append(" * Auto-generated JUnit test file for the W3C test suite: ");
        content.append(manifestUri);
        content.append("\n");
        content.append(" * This file was automatically generated by JUnitTestFileGenerator.java.\n");
        content.append(" * Generation date: ");
        content.append(LocalDate.now());
        content.append(", Time: ");
        content.append(nowWithZone.format(timeFormatter));
        content.append(" ");
        content.append(nowWithZone.getZone());
        content.append("\n");
        content.append(" */\n");

        // Class declaration
        content.append("public class ");
        content.append(fileName.substring(0, fileName.indexOf(".")));
        content.append(" {");
        content.append("\n");
        content.append("\n");

        // Watcher
        content.append(this.generateWatcher());

        // Test methods
        for (IW3cTest test : tests) {
            content.append(test.generate());
            content.append("\n");
        }

        // End of class
        content.append("}");

        return content.toString();
    }

    /**
     * Returns the package declaration based on the given path and file name.
     * 
     * @param path     The path of the file.
     * @param fileName The name of the file.
     * @return The package declaration.
     */
    private String getPackage(String path, String fileName) {
        String packagePath = path.substring(path.indexOf("java") + 5)
                .replace("/", ".")
                .replace("." + fileName, "");
        return "package " + packagePath + ";";
    }

    /**
     * Generates the watcher for the test file.
     * 
     * @return The watcher for the test file.
     */
    private String generateWatcher() {
        StringBuilder watcher = new StringBuilder();

        // Create a file testReport.csv in the directory of the test file
        Path relativePathToResultCsv = Paths.get(System.getProperty("user.dir")).relativize(exportPath)
                .resolve("testReport.csv");
        // Remove the first directory from the path
        relativePathToResultCsv = relativePathToResultCsv.subpath(1, relativePathToResultCsv.getNameCount());
        watcher.append("    private static final String TEST_REPORT_FILE = "
                + "Paths.get(System.getProperty(\"user.dir\")).resolve(\"" + relativePathToResultCsv.toString()
                + "\").toString();\n");
        watcher.append("    private static final String MANIFEST_URI = \""
                + manifestUri.toString().substring(0, manifestUri.toString().lastIndexOf(".")) + "\";\n");
        watcher.append("    private static final String EARL = \"http://www.w3.org/ns/earl#\";\n");
        watcher.append("\n");

        // Function to write the test report to the file testReport.csv
        // Format: manifestUri#testName, datetime, http://www.w3.org/ns/earl#status
        watcher.append("    /**\n");
        watcher.append("     * Writes the test report to the file testReport.csv.\n");
        watcher.append("     *\n");
        watcher.append("     * @param testName The name of the test.\n");
        watcher.append("     * @param success  The status of the test.\n");
        watcher.append("     */\n");
        watcher.append("    private void writeTestReport(String testName, String success) {\n");
        watcher.append("        try {\n");
        watcher.append("            Path testReportPath = Paths.get(TEST_REPORT_FILE);\n");
        watcher.append(
                "            DateTimeFormatter dtf = DateTimeFormatter.ofPattern(\"yyyy-MM-dd'T'HH:mm:ssXXX\");\n");
        watcher.append(
                "            Files.write(testReportPath, (MANIFEST_URI + \"#\" + testName + \",\" + dtf.format(ZonedDateTime.now()) + \",\" + EARL + success + \"\\n\").getBytes(), StandardOpenOption.APPEND);\n");
        watcher.append("        } catch (IOException e) {\n");
        watcher.append("            e.printStackTrace();\n");
        watcher.append("        }\n");
        watcher.append("    }\n");
        watcher.append("\n");

        watcher.append("    @Rule\n");
        watcher.append("    public TestWatcher watcher = new TestWatcher() {\n");
        watcher.append("\n");
        watcher.append("        @Override\n");
        watcher.append("        protected void failed(Throwable e, Description description) {\n");
        watcher.append("            writeTestReport(description.getMethodName(), \"failed\");\n");
        watcher.append("        }\n");
        watcher.append("\n");
        watcher.append("        @Override\n");
        watcher.append("        protected void succeeded(Description description) {\n");
        watcher.append("            writeTestReport(description.getMethodName(), \"passed\");\n");
        watcher.append("        }\n");
        watcher.append("\n");
        watcher.append("        @Override\n");
        watcher.append("        protected void skipped(AssumptionViolatedException e, Description description) {\n");
        watcher.append("            writeTestReport(description.getMethodName(), \"untested\");\n");
        watcher.append("        }\n");
        watcher.append("    };\n");
        watcher.append("\n");
        watcher.append("        // Create and clear the test report file\n");
        watcher.append("        @BeforeClass\n");
        watcher.append("        public static void createTestReportFile() {\n");
        watcher.append("            try {\n");
        watcher.append("                Path testReportPath = Paths.get(TEST_REPORT_FILE);\n");
        watcher.append("                Files.write(testReportPath, \"\".getBytes());\n");
        watcher.append("            } catch (IOException e) {\n");
        watcher.append("                e.printStackTrace();\n");
        watcher.append("            }\n");
        watcher.append("        }\n");
        watcher.append("\n");

        return watcher.toString();
    }

    private Set<String> defineImports() {
        Set<String> imports = new HashSet<>();
        imports.add("java.nio.file.Path");
        imports.add("java.nio.file.Paths");
        imports.add("java.nio.file.Files");
        imports.add("java.nio.file.StandardOpenOption");
        imports.add("org.junit.Rule");
        imports.add("org.junit.rules.TestWatcher");
        imports.add("org.junit.runner.Description");
        imports.add("org.junit.AssumptionViolatedException");
        imports.add("org.junit.BeforeClass");
        imports.add("java.time.format.DateTimeFormatter");
        imports.add("java.time.ZonedDateTime");
        return imports;
    }

}
