template st:start(?in) {
  st:call-template(?uri, ?desc)    
  
}
where {

  bind (unnest(st:errors(?in)) as ?e)
  bind (STRBEFORE(STRAFTER(?e, st:), "/") as ?type)
  bind (STRAFTER(STRAFTER(?e, st:), "/")  as ?desc)
    
values (?type ?uri) {
  ("owlel" st:mainEL)
  ("owlql" st:mainQL)
  ("owlrl" st:mainRL)
  ("owltc" st:mainOWL)
}    
} 