#
# Starting template for OWL pretty printing from RDF to Functional Syntax
# st:apply-all-templates run all templates on each value 
# Olivier Corby - Wimmics Inria I3S - 2013
#
template  st:body  {
    st:apply-templates(?t)  ; separator = "\n\n" 
}
where {

#  ?in a owl:Ontology 

  {select distinct ?t where {
    { ?t ?p ?y 
    filter (
      (isURI(?t) && ?y != owl:Ontology && ?p != owl:imports) ||
      # owl:AllDisjointClasses owl:NegativePropertyAssertion
      (isBlank(?t) && not exists { ?x ?q ?t } )
    )
  # OWL vocabulary must not be pretty printed
      filter (
          ! strstarts(?t, owl:) 
       && ! strstarts(?t, rdf:) 
       && ! strstarts(?t, rdfs:)
       && ! strstarts(?t, xsd:))
    }    
  }
  order by ?t}
        
}

