#
# Starting template for OWL pretty printing from RDF to Functional Syntax
# Olivier Corby - Wimmics Inria I3S - 2013
#
template st:html {
  st:call-template-with(st:server, st:head)
  
  "<h3>OWL Functional Syntax</h3>"
  "<pre>"
  st:call-template(st:start)
  "</pre>"
  
  st:call-template-with(st:server, st:tail)
}
where {
     bind(st:set(st:html, true) as ?ctx) 
}

