#
# RDF/XML Transformation
#
# Olivier Corby - Wimmics INRIA I3S - 2015
#

template st:focus(?in) {
  format { 
    """<pre>%s</pre>"""
    us:clean(st:call-template(st:start, ?in))
  }
  
}
where {
    bind (st:set(st:html, true) as ?b)
    bind (st:set(st:focus, false) as ?foc)
}

