prefix ft: <http://ns.inria.fr/sparql-template/format/rdfxml/>
template st:listtriple(?x, ?p, ?y) {
format {
   us:format(ft:property.html) 
   
   st:turtle(?p, true)
   box { st:call-template(st:listrec, ?y) }
}
}
where {
  
}
