#
# select top level terms ?in
# URI
# Top level bnodes (not object of a property)
#
template st:main2(?in) {
   if (st:visited(?in), "", 
    if (bound(?t), 
        st:call-template(st:resourcetype, ?in, ?t),
        st:call-template(st:resource, ?in)))
    
   ; separator = "\n\n"
}
where {
   select distinct ?in ?t where {
     bind (st:focus() as ?in)
     ?in ?p ?y
     
     filter (isBlank(?in) && ! st:visited(?in))
     
     optional {
        select ?in ?t where {
            ?in a ?t  
            filter (! isBlank(?t))
        } limit 1
     }
     
   }
   order by ?in
}
