#
# RDF/XML Transformation
#
# Olivier Corby - Wimmics INRIA I3S - 2015
#
prefix ft: <http://ns.inria.fr/sparql-template/format/rdfxml/>

template st:start(?in) {
format {
  us:format(ft:head.html)  
  ibox { st:call-template(st:prefix) }
  str(?body)  
}
}
where {
   bind(
    if (bound(?in), st:call-template(st:main, ?in), st:call-template(st:main)) 
   as ?body )
}
