#
# Link to external web site (eg Wikipedia)
#
prefix ft:  <http://ns.inria.fr/sparql-template/format/navlab/>

template  st:href(?r, ?p) {
  format {
  
  ft:link.html

   str(?v) str(?v) 
  }
}

where {
   ?r ?p ?v 
}
 
