#
# Geolocate resource on a map given lat et long
#
prefix p: <http://fr.dbpedia.org/property/>
prefix o: <http://dbpedia.org/ontology/>

template st:locate {

  st:call-template(st:map, ?in, ?lat, ?lon)
  
}
where {
  ?in a o:Place 
  {select * where { 
  # let o:place first because limit 1
    { ?in o:place [ 
	p:longitude ?lon ;
	p:latitude  ?lat]   
    } 
    union
    {?in p:longitude ?lon ;
	 p:latitude  ?lat }     
  } limit 1}
}