#
# Geolocate resource on a map given lat et long
#

template st:map(?r, ?lat, ?lon) {

  if (st:get(st:protocol, st:ajax), "", 
  """<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>""")

"""
  <script>
  function callback() {
    var pos = new google.maps.LatLng("""  str(?lat) "," str(?lon) ");"
      
    """  
    var mapOptions = {zoom: 7, center: pos, mapTypeId: google.maps.MapTypeId.TERRAIN};
            
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    
    google.maps.event.addListener(map, 'click', 
    function( event ){
      alert( "p:latitude: " + event.latLng.lat() + " " + "; p:longitude: " + event.latLng.lng() ); 
    });
    
    var marker = new google.maps.Marker({ position: pos, map: map, icon: '/img/bmarker.png' });
"""
    
    st:call-template(st:locateall, ?r)
    
"}"

    if (st:get(st:protocol, st:ajax), "",
        "google.maps.event.addDomListener(window, 'load', callback);")

"""
  </script>
      
  <p id="map-canvas" ></p>
  """
}
where {
  
}