prefix o:    <http://dbpedia.org/ontology/>
prefix w:    <http://fr.wikipedia.org/wiki/>
prefix r:    <http://fr.dbpedia.org/resource/>
prefix p:    <http://fr.dbpedia.org/property/>

template {

  st:call-template(st:title, ?r, ?label, (coalesce(?ic, "")))
  
  
  """<table>
  """  
  
  st:call-template(st:descplace, ?r)
    
  """</table>
  """
  
  st:call-template(st:locate, ?in, ?lat, ?lon)

}
where {

  ?in a o:Place
  minus { ?in a o:Resource }
  
  bind (?in as ?r)
  
  ?r rdfs:label ?label 
  	      
  optional { ?r o:thumbnail  ?ic  }
  
  bind (concat(w:, (substr(?r, strlen(r:) + 1))) as ?pr)   

  optional {
    ?in p:longitude ?lon ;
	p:latitude  ?lat
  }
}
