//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 10:15:40 AM CEST 
//


package fr.inria.corese.rif.xml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import fr.inria.corese.rif.ast.Annotation;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.w3.org/2007/rif#}Frame"/>
 *         &lt;element name="And" type="{http://www.w3.org/2007/rif#}And-meta.type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "frame",
    "and"
})
@XmlRootElement(name = "meta")
public class Meta {

    @XmlElement(name = "Frame")
    protected Frame frame;
    @XmlElement(name = "And")
    protected AndMetaType and;

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link Frame }
     *     
     */
    public Frame getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame }
     *     
     */
    public void setFrame(Frame value) {
        this.frame = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link AndMetaType }
     *     
     */
    public AndMetaType getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link AndMetaType }
     *     
     */
    public void setAnd(AndMetaType value) {
        this.and = value;
    }
    
    public Annotation XML2AST() {
		Annotation a ;
		if(this.getFrame() != null) {
			a = Annotation.create(this.getFrame().XML2AST()) ;
			//TODO
		} else if (this.getAnd() != null) {
			a = Annotation.create(this.getAnd().XML2AST()) ;
		} else {
			a = Annotation.create() ;
		}
		return a ;
	}

}
