prefix sp:      <http://spinrdf.org/sp#> .
template st:page {

  "<h3>SPARQL-SPIN Translator</h3>"
  
   if (contains(st:get(st:service),  "tospin"),
     st:call-template(st:tospin),
     st:call-template(st:tosparql))
  
}
where {

}
