template st:table {

 "<tr>"
 "<th>"      st:number()
 "</th><td>" st:call-template(st:linkesc, ?x) 
 "</td><td>" st:call-template(st:esc, ?p) 
 "</td><td>" st:call-template(st:linkesc, ?y) 
 "</td>"
 "</tr>"
 
}
where {
  ?x ?p ?y
  filter (?x = coalesce(st:get(st:uri), ?x))
}
order by ?x ?p ?y